Updated IBM/Lenovo OS definitions for proper detection + LLDP Mappings
librenms/librenms pull request #12020
Opened 2020-08-19 14:22 UTC by fz883

Please give a short description what your pull request is for:

IBM sold their Networking business to Lenovo back in ~2015 or so. With that Lenovo inherited switches like the G8052 and others that, starting with FW version 8.x were rebranded to Lenovo. The mibs are the same, but the device are actually Lenovo branded. In order to rebrand those switches in LibreNMS to Lenovo to distinguish between them, I created a new OS called "enos" - [link](https://www.lenovo.com/medias/lenovo-enterprise-networking-os-ds.pdf?context=bWFzdGVyfC9lbWVhL3BkZi9zaXRlbWFwL3wxMzM5MzN8YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtfC9lbWVhL3BkZi9zaXRlbWFwL2hlZC9oNzYvOTM4OTAxNjI4NTIxNC5wZGZ8ZGNmYWYyZTc3MzhhYjFkN2QyZTgyMTYwZDRiMjQ0YWQzZThhOWM0Zjk0MDVlZTkxZDE2NWZlMGU0MWQyZGY1Nw). Before that, Lenovo rebranded IBM switches were shown as generic devices in the device overview of LibreNMS with no OS info, no FW version, no serial info.

The CNOS (pure Lenovo FW) definition was updated to gather FW version + serial. After that, the overview shows all device types correctly.

![image](https://user-images.githubusercontent.com/1890156/90646242-4a8c2a80-e237-11ea-93b8-e7dd168a02b3.png)

I also updated the discovery-protocols.php file to incorporate some changes needed in order to get LLDP mappings correct. Before that some links from CNOS to ENOS devices were not "linked" to the remote switch & port because the ports were not found in the DB. If the changes I made are in the wrong spot, please advise. After the change the LLDP and network mappings are fine, the generated map shows all devices correctly linked.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2020-08-19 14:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=12020) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=12020) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=12020) it.</sub>

2020-08-19 14:36 UTC, fz883 commented
ok, Travis fails because snmprec files are not available. please advise on those,

2020-08-19 15:27 UTC, Jellyfrog requested changes

2020-08-19 15:27 UTC, Jellyfrog commented on includes/polling/os/cnos.inc.php
> +$sysdescr_value = $device['sysDescr'];
these should be converted to the new OS format, see for example https://github.com/librenms/librenms/blob/master/LibreNMS/OS/Endrun.php

2020-08-19 15:27 UTC, Jellyfrog commented on includes/polling/os/enos.inc.php
> +<?php
dito

2020-08-19 15:28 UTC, Jellyfrog commented
I don't think we need all those MIBs

2020-08-19 15:29 UTC, Jellyfrog commented
it also fails on syntax, https://travis-ci.com/github/librenms/librenms/jobs/375363635

2020-08-20 14:19 UTC, murrant commented
Yes, standard mibs should not be included in vendor directories.

2021-02-02 00:09 UTC, Jellyfrog commented
Thank you for your contribution but we're closing this due to inactivity.  
Feel free to reopen if you plan on finishing it!

2021-02-02 00:09 UTC, closed without merging