osnexus quantastor initial support
librenms/librenms pull request #12045
Opened 2020-08-31 21:22 UTC by crcro

added quantastor support 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

please bear with me ... long time no see :)
also the osnexus mib is very "detailed" and at this moment i don't have anything in error to get the states code

before:
![quantastor_before](https://user-images.githubusercontent.com/3048315/91770053-2a6e4b00-ebe9-11ea-8768-39cd31677dbc.png)

after:
![quantastor_after](https://user-images.githubusercontent.com/3048315/91770082-36f2a380-ebe9-11ea-998e-198f26818215.png)
![quantastor_disk_temp](https://user-images.githubusercontent.com/3048315/91770091-38bc6700-ebe9-11ea-95e0-27cf22bf9c78.png)
![quantastor_states](https://user-images.githubusercontent.com/3048315/91770095-3954fd80-ebe9-11ea-9d3b-9a9d3105026e.png)

2020-08-31 22:28 UTC, Jellyfrog requested changes

2020-08-31 22:28 UTC, Jellyfrog commented on html/images/logos/quantastor.svg
> +    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAMAAABrrFhUAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
This svg just embeds a png. Either find a real svg (Best option) or change to a png.

2020-08-31 22:28 UTC, Jellyfrog commented on html/images/os/quantastor.svg
> +    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAMAAABrrFhUAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
Ditto.

2020-08-31 22:28 UTC, Jellyfrog commented on includes/polling/os/quantastor.inc.php
> +<?php
This needs to be ported to the new OS format, see https://github.com/librenms/librenms/blob/master/LibreNMS/OS/Qnap.php for example.

2020-09-01 04:20 UTC, TheGreatDoc commented
Please remove the extension to the mib file and put it in vendor directory (ex: mibs/osnexus/QUANTASTORE-SYS-STATS) then you have to add the mib_dir to the definition yaml.

Another question: Did you try to use yaml discovery instead php? I see you get tables and that should work with yaml.

2020-09-01 10:55 UTC, crcro commented
> 
> 
> Please remove the extension to the mib file and put it in vendor directory (ex: mibs/osnexus/QUANTASTORE-SYS-STATS) then you have to add the mib_dir to the definition yaml.
> 
> Another question: Did you try to use yaml discovery instead php? I see you get tables and that should work with yaml.

Initially i went with yaml but could not get the description field formed (probabily i did something wrong):
- i want the description formed by 2 snmp values (disk-slot and disk-serial): Disk <<slot>> SN: <<serial>> but couldn't make it work

2020-09-01 11:35 UTC, TheGreatDoc commented
> * i want the description formed by 2 snmp values (disk-slot and disk-serial): Disk <> SN: <> but couldn't make it work

Then what you need is to pre-cache that table.

2020-09-01 11:43 UTC, crcro commented
I tried with pre-cache-ing table, but i could not get all that vars concatenation, like my {{ $diskSlot-Name }} would be printed as-is on webui instead of it's value.

tried something like:
descr: '{{ $diskSlot-Name }} SN: {{ $diskSlot-Serial }}'

2020-09-01 11:47 UTC, TheGreatDoc commented
Yeah, sometimes is a bit hard.

Take a look here https://github.com/librenms/librenms/pull/11882/files#diff-2faf551b4d6c42759cffb28a157d32b9

I said pre-cache table but I think you have to set directly oids. So try pre-caching diskSlot-Name and play with that

2020-09-02 13:21 UTC, Jellyfrog commented
@crcro that test-data doesnt look so good, please re-run and dont forget step 2, https://docs.librenms.org/Developing/os/Test-Units/#capturing-test-data

2020-09-05 00:28 UTC, crcro commented
@TheGreatDoc ... moved to YAML, found out the issue in values names (they have - in name and YamlDiscovery.php would not match them)
@Jellyfrog ... hope that they are ok now

2020-09-05 10:11 UTC, Jellyfrog approved these changes

2020-09-05 10:15 UTC, Jellyfrog commented
@crcro it still doesn't match it sadly. It matches the generic Linux os instead

2020-09-05 14:01 UTC, crcro commented
this is strange .... if i run ./discovery.php with -d it matches the os and discovers all the sensors as defined, but without -d it reverts it to linux

2020-09-05 15:12 UTC, Jellyfrog commented
Did you delete the os cache first?  
rm -f cache/os_defs.cache

2020-09-06 12:20 UTC, crcro commented
@Jellyfrog .... sure thing 

librenms@graph:~$ rm -fr cache/os_cache
librenms@graph:~$ ./discovery.php -h 143 -d -m os 
get the following:
Device type changed to storage!
Attempting to initialize OS: quantastor
OS initialized: LibreNMS\OS\Quantastor
OS: QuantaStor (quantastor)

but as soon as i run:
librenms@graph:~$ ./discovery.php -h 143 -m os
LibreNMS Discovery
<<hostname>> 143 quantastor
#### Load disco module core ####
Changed OS: Linux (linux)

2020-09-07 15:12 UTC, murrant commented on LibreNMS/OS/Quantastor.php
> +        unset($info);
unset does nothing here, because $info goes out of scope when leaving the function...

2020-09-07 15:13 UTC, murrant commented on includes/definitions/quantastor.yaml
> +discovery_modules:
Please don't disable modules at the OS level, especially ones that are disabled by default.

2020-09-07 22:38 UTC, crcro commented
strange travis always fails but on local:

```
librenms@graph:~$ ./lnms dev:check -o quantastor
Only checking os: quantastor
Running unit check...
Starting snmpsim listening on 127.1.6.2:1162...
Refreshing database...done
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.

........                                                            8 / 8 (100%)

Time: 1.11 minutes, Memory: 72.25 MB

OK (8 tests, 1496 assertions)
success (67.46s)
librenms@graph:~$
```

2020-09-08 12:51 UTC, Jellyfrog commented
The initial build problem has been fixed, now you have some other problems, https://travis-ci.com/github/librenms/librenms/jobs/382090323

2020-09-08 19:27 UTC, crcro commented
travis here still fails ... 
```
ibrenms@graph:~$ ./lnms dev:check -o quantastor
Only checking os: quantastor
Running unit check...
Starting snmpsim listening on 127.1.6.2:1162...
Refreshing database...done
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.

........                                                            8 / 8 (100%)

Time: 1.07 minutes, Memory: 70.25 MB

OK (8 tests, 1496 assertions)
success (64.96s)
librenms@graph:~$
```

2020-09-10 09:00 UTC, Jellyfrog commented
We're seeing different results, and I believe it's related to something else...
Could you please run:

```sh
$ php -v
PHP 7.4.8 (cli) (built: Jul 13 2020 16:46:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies

$ mysql -V
mysql  Ver 8.0.20-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

$ snmpget -V
NET-SNMP version: 5.8

$ snmpsimd.py --version
SNMP Simulator version 0.4.7, written by Ilya Etingof <etingof@gmail.com>
Using foundation libraries: pysnmp 4.4.12, pyasn1 0.4.2.
Python interpreter: 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]

```

2020-09-10 15:35 UTC, crcro commented
```
root@graph:/opt/librenms# php -v
PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.6, Copyright (c) 1999-2018, by Zend Technologies
root@graph:/opt/librenms#

root@graph:/opt/librenms# mysql -V
mysql  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
root@graph:/opt/librenms#

root@graph:/opt/librenms# snmpget -V
NET-SNMP version: 5.7.3
root@graph:/opt/librenms#

root@graph:/opt/librenms# snmpsimd.py --version
SNMP Simulator version 0.4.7, written by Ilya Etingof <etingof@gmail.com>
Using foundation libraries: pysnmp 4.4.12, pyasn1 0.4.8.
Python interpreter: 2.7.17 (default, Jul 20 2020, 15:37:01)
[GCC 7.5.0]
Software documentation and support at http://snmplabs.com/snmpsim
Usage: /usr/local/bin/snmpsimd.py [--help]
    [--version ]
    [--debug=<mibbuild|all|app|msgproc|proxy|io|secmod|dsp|acl|mibinstrum>]
    [--debug-asn1=<none|decoder|all|encoder>]
    [--daemonize]
    [--process-user=<uname>] [--process-group=<gname>]
    [--pid-file=<file>]
    [--logging-method=<syslog|null|stderr|file|stdout[:args>]>]
    [--log-level=<debug|info|error>]
    [--cache-dir=<dir>]
    [--variation-modules-dir=<dir>]
    [--variation-module-options=<module[=alias][:args]>]
    [--force-index-rebuild]
    [--validate-data]
    [--args-from-file=<file>]
    [--transport-id-offset=<number>]
    [--v2c-arch]
    [--v3-only]
    [--v3-engine-id=<hexvalue>]
    [--v3-context-engine-id=<hexvalue>]
    [--v3-user=<username>]
    [--v3-auth-key=<key>]
    [--v3-auth-proto=<MD5|SHA|SHA224|SHA256|SHA384|SHA512>]
    [--v3-priv-key=<key>]
    [--v3-priv-proto=<3DES|AES|AES128|AES192|AES192BLMT|AES256|AES256BLMT|DES>]
    [--data-dir=<dir>]
    [--max-varbinds=<number>]
    [--agent-udpv4-endpoint=<X.X.X.X:NNNNN>]
    [--agent-udpv6-endpoint=<[X:X:..X]:NNNNN>]
    [--agent-unix-endpoint=</path/to/named/pipe>]
root@graph:/opt/librenms#

```

2020-09-11 13:14 UTC, Jellyfrog commented
@crcro I think it fails because your `config.php` have ignore settings defined, like so, https://docs.librenms.org/Developing/os/Settings/#ignoring-interfaces

2020-09-13 21:44 UTC, Jellyfrog approved these changes

2020-09-13 21:45 UTC, merged

2020-09-30 03:18 UTC, murrant commented
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1