Add attach sysName to Prometheus option.
librenms/librenms pull request #12061
Opened 2020-09-06 09:10 UTC by jasoncheng7115

The value of put to prometheus can be added to sysName by setting the relevant parameter.

This will make the display of LibreNMS Devices on Prometheus and Grafana more user-friendly.

config.php adding the setting entry:
```$config['prometheus']['attach_sysname'] = true;``` 

which allows put to Prometheus to add sysName content, for example:
`ping{instance="192.168.1.140",job="librenms",measurement="ping-perf",sysName="metric1"} 0.15`

  
  

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2020-09-06 12:47 UTC, Jellyfrog commented
Please add settings like so https://docs.librenms.org/Developing/Dynamic-Config/

2020-09-06 12:55 UTC, Jellyfrog requested changes
Please add settings like so https://docs.librenms.org/Developing/Dynamic-Config/

2020-09-07 02:41 UTC, jasoncheng7115 commented
> Please add settings like so https://docs.librenms.org/Developing/Dynamic-Config/

Thank you very much. I've fix it.

2020-09-07 11:04 UTC, Jellyfrog commented
Missing a `./lnms translation:generate` to generate translations, while at it, could you also add translations for `job` and `url` ?

2020-09-07 11:05 UTC, Jellyfrog commented on resources/lang/en/settings.php
>              ]
```suggestion
            ],
```

2020-09-07 15:17 UTC, jasoncheng7115 commented
> Missing a `./lnms translation:generate` to generate translations, while at it, could you also add translations for `job` and `url` ?

Thanks, the prometheus.url and prometheus.job translations have been fixed.

![image](https://user-images.githubusercontent.com/30381035/92401399-277ed780-f160-11ea-8f4c-125b254de1f5.png)

2020-09-07 19:38 UTC, Jellyfrog approved these changes
Thanks

2020-09-07 19:38 UTC, merged

2020-09-30 03:18 UTC, murrant commented
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1