new index in alert_log table
librenms/librenms pull request #12143
Opened 2020-09-22 14:28 UTC by Negatifff

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2020-09-22 14:29 UTC, Negatifff commented
trying to add this query
`create index `rule_and_device` on alert_log (`rule_id`,`device_id`);`
I hope I did everything right

2020-09-22 17:08 UTC, bofh80 commented
class AddDevicePerfIndex extends Migration
you want to change to that a new unique name like:
class AddAlertLogNewIndex extends Migration
￼(assuming that's not in use too i did not check :) )

2020-09-22 17:25 UTC, Negatifff commented
Thanks, didn't notice

2020-09-22 23:37 UTC, bofh80 commented
i'm not 100% sure but maybe:
$table->index(['rule_id', 'device_id'], 'alert_log_rule_and_device_index');

But that's a *guess* .

2020-09-23 08:33 UTC, Negatifff commented
> i'm not 100% sure but maybe:
> $table->index(['rule_id', 'device_id'], 'alert_log_rule_and_device_index');
> 
> But that's a _guess_ .

I did by analogy with database/migrations/2020_07_29_143221_add_device_perf_index.php

2020-09-23 11:37 UTC, Jellyfrog requested changes

2020-09-23 11:37 UTC, Jellyfrog commented on database/migrations/2020_09_22_172321_add_alert_log_index.php
> +        });
```suggestion
        Schema::table('alert_log', function (Blueprint $table) {
            $table->index(['rule_id', 'device_id']);
            $table->index(['rule_id', 'device_id', 'state']);
        });
```

2020-09-23 11:37 UTC, Jellyfrog commented on database/migrations/2020_09_22_172321_add_alert_log_index.php
> +        });
```suggestion
        Schema::table('alert_log', function (Blueprint $table) {
            $table->dropIndex(['rule_id', 'device_id']);
            $table->dropIndex(['rule_id', 'device_id', 'state']);
        });
```

2020-09-23 11:54 UTC, Negatifff commented on database/migrations/2020_09_22_172321_add_alert_log_index.php
> +        });
thanks

2020-09-24 15:05 UTC, Jellyfrog approved these changes

2020-09-24 15:05 UTC, merged

2020-09-30 03:18 UTC, murrant commented
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1