Change of default .pdf font
librenms/librenms pull request #12278
Opened 2020-10-29 18:41 UTC by p4k8

Change of TCPDF font from helvetica to freeserif to support wider variety of languages by default (including cyrillic). Causes "??????" to render correctly.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2020-10-30 12:54 UTC, Jellyfrog requested changes
Thats not a common font to have installed as far as I know, dejavu versions would be far more common, and should be added to the install instructions also.

2020-10-30 13:31 UTC, p4k8 commented
Instead of system fonts TCPDF uses font files included in its [font directory](https://github.com/tecnickcom/TCPDF/tree/main/fonts)
Where `freeserif` is in fact included by default along with `helvetica`, so system installed fonts coverage shouldn't matter.

2020-10-30 13:39 UTC, p4k8 commented
And there seems to be no objective preference btw, just tested `dejavusans` (also default one), works with cyrillic as well.
So whichever you prefer :)

2020-11-01 00:19 UTC, Jellyfrog commented
My bad, I don't have any preferences really

2020-11-01 00:24 UTC, Jellyfrog approved these changes

2020-11-01 00:24 UTC, merged

2020-11-02 03:25 UTC, murrant commented
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-release-changelog-october-2020/13837/1