Checkpoint VSX: Added HA state support
librenms/librenms pull request #12382
Opened 2020-12-06 20:56 UTC by lazyb0nes

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2020-12-07 11:29 UTC, calinrigo approved these changes
It would be great to integrate the HA state support

2020-12-08 07:42 UTC, f0o commented
@calinrigo have you been able to test these changes and verify that they work?

2020-12-10 08:35 UTC, lazyb0nes commented
I am guessing someone else also has to check but i have at least two generations of Checkpoint that i've tested it on and it works as intended.

2020-12-10 09:30 UTC, calinrigo commented
Just discovered that if you are running Checkpoint on Dell Appliances this HA State will not work.
Here is part of the discovery capture.

`NMP['/usr/bin/snmpget' '-v3' '-l' 'authNoPriv' '-n' "" '-a' 'MD5' '-A' 'PASSWORD' '-u' 'USER' '-OUQ' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/checkpoint' 'udp:HOSTNAME:161' 'CHECKPOINT-MIB::svnApplianceProductName.0' 'CHECKPOINT-MIB::svnApplianceSerialNumber.0' 'CHECKPOINT-MIB::svnVersion.0']

CHECKPOINT-MIB::svnApplianceProductName.0 = PowerEdge R740
CHECKPOINT-MIB::svnApplianceSerialNumber.0 = 
CHECKPOINT-MIB::svnVersion.0 = R80.30  
  

Yaml OS data: {"CHECKPOINT-MIB::svnApplianceProductName.0":"PowerEdge R740","CHECKPOINT-MIB::svnApplianceSerialNumber.0":"","CHECKPOINT-MIB::svnVersion.0":"R80.30"} 

Location: Unknown

Hardware: PowerEdge R740

OS Version: R80.30

OS Features: 

Serial: 


>> Runtime for discovery module 'os': 0.0630 seconds with 9304 bytes`

2020-12-10 09:59 UTC, calinrigo commented
I think I got that wrong...
Checkpoint is a quite complicated beast.
I was testing your code againsts a checkpoint VSX cluster...

Trying to extend on what you did there on adding VSX cluster support.
As this is the first time doing this...I might not know what I'm doing here :P

2020-12-10 10:04 UTC, lazyb0nes commented
This code will only work with Check Point VSX

VSX is only the hardware in this case i have tested it against:
**Check Point 23900 
Check Point 15600**

https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk90860&partition=General&product=Security

If you go under 
**VSX** and **Cluster**

2020-12-10 10:42 UTC, calinrigo commented
There was a problem on my deployment.
It works now!
I have the HA state.
@f0o I can confirm it works on my side also.

2020-12-10 10:54 UTC, lazyb0nes commented
> There was a problem on my deployment.
> It works now!
> I have the HA state.
> @f0o I can confirm it works on my side also.

Sot the HA state also works on a virtual Check Point appliance?

2020-12-14 09:38 UTC, f0o submitted a review, later dismissed
LGTM

@librenms/testers if anyone has related devices and could double check that would be great. But it seems to be fine from above comments.

2021-01-07 14:09 UTC, epacke commented
Need to update the old tests too I reckon. Coffee break is over. Will do that tonight.

2021-01-07 19:04 UTC, epacke commented
@Jellyfrog About to break my keyboard in two and jump out of the window. It's on the bottom floor but it's COLD in Stockholm so it will still suck! GAH!!

I _think_ this is due to some locale or something like that. Seems like the rounding of numbers differ between my local instance and the one running the unit test. Have you seen this before?

2021-01-08 18:53 UTC, epacke commented
Now it builds but the new sensors is not included in the json files. ** screaming into  a pillow **

2021-01-08 19:17 UTC, epacke commented
Order is restored. I'm out of options now.

2021-01-09 03:19 UTC, murrant requested changes

2021-01-09 03:19 UTC, murrant commented on includes/definitions/discovery/gaia.yaml
> +                        - { value: 3, descr: ´active attention´, graph: 1, generic: 1 }
the backticks here are not correct

2021-01-09 03:19 UTC, murrant commented on includes/definitions/discovery/gaia.yaml
> +                    descr: "Cluster mechanism started"
please use single quotes for consistency

2021-01-09 03:19 UTC, murrant commented on includes/definitions/discovery/gaia.yaml
> +                    descr: "Cluster member state"
single quotes here

2021-01-09 03:19 UTC, murrant commented on includes/definitions/discovery/gaia.yaml
> +                    descr: "Cluster member status code"
and single quotes here.

2021-01-10 23:21 UTC, Jellyfrog approved these changes

2021-01-10 23:22 UTC, merged

2021-02-03 06:19 UTC, chrisrnz commented
This feature caused me some grief today, but I have a fleet of Check Point devices and a few different types in the mix.

The Clustered machines (pairs of 5600's) seemed to be happy after the sensors were added.

But then there were the dozens of branch office appliances (1430's) that all had the %macros.state_sensor_critical rule throwing alerts for "sensor_id = 544; sensor_oid = .1.3.6.1.4.1.2620.1.5.5.0;   sensor_descr = Cluster mechanism started; state_descr = no;"

Note: These are little embedded boxes (small office) style that run a different OS to the big ones.

The ha state sensors in health settings look like this to me.
Normal GAiA FW, clustered.
One member
state	haStarted	Cluster mechanism started	1	
state	haStatCode	Cluster member status code	0	
state	haState	Cluster member state	2
Other member
state	haStarted	Cluster mechanism started	1	
state	haStatCode	Cluster member status code	0	
state	haState	Cluster member state	1
Looks good

The little GAiA Embedded box, these are standalone, not clustered.
state	haStarted	Cluster mechanism started	0	
state	haStatCode	Cluster member status code	2

I'm happy to provide any further info that might be useful to help try fix this, just let me know what/how. :)

Cheers.
C.