Fixes issues with binding and authenticating users in nested groups
librenms/librenms pull request #12398
Opened 2020-12-15 10:18 UTC by paddy01

Signed-off-by: Patrik Forsberg <paddy@paddyonline.net>

Please give a short description what your pull request is for

After having a few issues with authenticating users with our Active Directory I created these modifications and they seem to be working as intended.
In the function bind it returns the result from $bind_result to the requesting module if it is true - which returned "null" pre-patch making active directory bind fail.
In the function userInGroup a bit of code that seem obsolete has been cut away and return value is now derived from ldap_get_entries in the initial search - which seems to be doing what the obsolete code was doing and by doing it again it actually broke authentication.

Using PHP 7.3 and not 7.0 might have something to do with it.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [-] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2020-12-15 10:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=12398) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=12398) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=12398) it.</sub>

2020-12-16 14:33 UTC, murrant commented
The return $bind_result makes little sense to me because no calls to the bind function expect a return value.
Also, it looks like after you removed that code from the userInGroup function it seems to only check if the group exists... which is not a good thing.

2020-12-16 15:10 UTC, paddy01 commented
> The return $bind_result makes little sense to me because no calls to the bind function expect a return value.

I'm not sure if it is only the test tool that needs it or not but without returning the value the test tool returns " Could not bind to AD, you will not be able to use the API or alert AD users " but with the return of $return_value (which would be the same as returning true) " AD bind success " - so _something_ is using the return value.

> Also, it looks like after you removed that code from the userInGroup function it seems to only check if the group exists... which is not a good thing.

You could be correct.. I never dug deep enough to look closer to what userInGroup actually does .. but I am sure that a user with the wrong group is not allowed and it is used to determine which level the user will get, I have two different groups where one get level 5 and one 10 and even though the user is part of both groups the user gets the "higher" level. And if the user is not part of any allowed groups the user gets rejected.
So after checking a bit even tho it no longer verify that the user is part of the group it verifies that the user is part of the correct DN, which is a plus. Other parts verify that the user is part of the correct group it seems, the name for userInGroup might be wrong after the change tho...

2021-01-07 03:01 UTC, murrant commented
@paddy01 I got around to testing this.  Mostly it worked great, but I found one issue.  When you are in multiple approved groups, your final access should be the highest access of all groups you are in.

2021-01-07 03:04 UTC, murrant requested changes
@paddy01 I got around to testing this. Mostly it worked great, but I found one issue. When you are in multiple approved groups, your final access should be the highest access of all groups you are in.

2021-01-07 14:15 UTC, paddy01 commented
> @paddy01 I got around to testing this. Mostly it worked great, but I found one issue. When you are in multiple approved groups, your final access should be the highest access of all groups you are in.

@murrant actually my patch is faulty and probably opens some security issue. I found the real issue and will update my poll request with a real fix for the issue. I've re-instated the group check but kept the return result in the bind function.
As for the use of highest level if a user is part of multiple groups is, from what I can understand in the code, by design .. in the function "getUserlevel" the line " max($userlevel, $level['level']) " would pick the highest possible level among those the user is part of - quite logical but that is the reason.

2021-02-02 05:42 UTC, murrant commented on LibreNMS/Authentication/ActiveDirectoryAuthorizer.php
> +        $ldap_find_chr = [];
please don't define an array like this.  Do this:
```php
        $ldap_find_chr = ['(', ')'];
        $ldap_replace_chr = ['\(', '\)'];
```

2021-02-02 05:43 UTC, murrant commented on LibreNMS/Authentication/ActiveDirectoryAuthorizer.php
> +        $group_dn = str_replace($ldap_find_chr, $ldap_replace_chr, $result[0]['dn']);
Additionally, just use this:

`$group_dn = addcslashes($result[0]['dn'], '()');`

2021-02-02 05:46 UTC, murrant approved these changes

2021-02-02 06:13 UTC, merged