webui: Add button to show verbose alert details in the alert, alert-log webui
librenms/librenms pull request #12484
Opened 2021-01-30 15:01 UTC by theochita

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2021-01-30 15:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=12484) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=12484) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=12484) it.</sub>

2021-01-30 15:02 UTC, theochita commented
Based on Murrants comment in https://github.com/librenms/librenms/pull/12413

2021-01-30 15:31 UTC, theochita commented
![image](https://user-images.githubusercontent.com/28762951/106360389-12bdfe80-6310-11eb-8898-db4a60e43016.png)

![image](https://user-images.githubusercontent.com/28762951/106360416-3bde8f00-6310-11eb-8dd9-0a609e4d2811.png)

2021-02-01 20:19 UTC, Jellyfrog requested changes

2021-02-01 20:19 UTC, Jellyfrog commented on includes/html/common/alert-log.inc.php
>              <th data-column-id="hostname">Device</th>
All files have the wrong permissons

2021-02-03 10:15 UTC, theochita commented on includes/html/common/alert-log.inc.php
>              <th data-column-id="hostname">Device</th>
should have fixed the permissions now.

2021-02-03 13:51 UTC, TheMysteriousX commented
This change allows unprivileged users to view credentials used for device access - is this intended?

2021-02-03 14:28 UTC, theochita commented
> This change allows unprivileged users to view credentials used for device access - is this intended?
When i copy a successful call to the ajax_form type "alert-details" and then logout and try again i get Unauthorized.

It is correct that it is not doing any user permission checks itself, normal users would be able to use it if they have the device permissions, giving them access to the community string so could be a potential source of leaks.

Making it global admin only is a possibility.

2021-02-05 14:28 UTC, theochita commented
I made the use of this feature require admin permissions as per what @TheMysteriousX pointed out, better safe than sorry.

2021-02-11 23:26 UTC, Jellyfrog commented
The tests fails

2021-02-12 01:34 UTC, murrant commented on includes/html/common/alert-log.inc.php
> +    $admin_verbose_details = '<th data-column-id="verbose_details" data-sortable="false">Details</th>';
This only prevents the link from showing up, the details are still in the html below.  You'll need to add a check down there too.

2021-02-13 15:48 UTC, theochita reviewed
all tests passing.

2021-03-04 10:37 UTC, theochita commented
Anything else i can do?

2021-03-05 14:01 UTC, murrant approved these changes
I'd prefer not to add legacy frontend code, but lgtm.

2021-03-06 20:56 UTC, Jellyfrog approved these changes

2021-03-06 20:57 UTC, merged