Nokia sap improvements
librenms/librenms pull request #12563
Opened 2021-02-25 08:23 UTC by meitianlia

This pull request is for Nokia sap improvements.

1, Sum the ingress and egress traffic.
2, Calculate and show the VLAN values when the port is in access without encapsulation or Dot1q or QinQ mode.

Previous page:
![Screenshot from 2021-02-25 20-40-04](https://user-images.githubusercontent.com/55170590/109124243-8f2ceb80-77af-11eb-8ea3-60ba8a086734.png)

After the changes:
![Screenshot from 2021-02-25 20-35-04](https://user-images.githubusercontent.com/55170590/109124274-9bb14400-77af-11eb-92ae-b99a97bbcb57.png)

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2021-02-25 08:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=12563) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=12563) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=12563) it.</sub>

2021-02-25 12:15 UTC, Jellyfrog commented
This seems to change the output, so can you please generate new test data?

2021-02-26 15:11 UTC, Jellyfrog commented
@craig-nokia any input?

2021-02-26 22:11 UTC, craig-nokia commented
> @craig-nokia any input?

Patch is good when you look at individual routers sap encapsulation.
http://localhost/device/63/routing/proto=mpls/view=saps/

But for the global sap view with all the routers, it is still showing the wrong encapsulation.
For the http://localhost/routing/protocol=mpls/view=saps/

I assume that updates to includes/html/pages/routing/mpls.inc.php should be applied.

2021-02-26 22:48 UTC, Channing-Jiang commented
@craig-nokia Thanks, forgot to update the global sap view. Just done that.

2021-02-26 23:24 UTC, craig-nokia commented
> @craig-nokia Thanks, forgot to update the global sap view. Just done that.

Patch is good to go.  

But, I don't understand why the tests failing are for a simple update to a webpage display.

2021-02-27 01:14 UTC, Jellyfrog commented on includes/html/pages/device/routing/mpls.inc.php
> +        }
Since this now exists in two places, please move it to a function

2021-02-27 01:15 UTC, Jellyfrog commented on includes/html/pages/device/routing/mpls.inc.php
> +        if ($showSapEncapValue == 0 and $showSapEncapValue != '*') {
use `&&` instead of and

2021-02-27 09:45 UTC, craig-nokia commented
Reapplied the patch and looks good.

2021-03-01 21:43 UTC, Channing-Jiang commented
@Jellyfrog Thanks for the advise and review. I did another patch for the sap graph page to show the correct title, should I open another pull request or just push it to here?

2021-03-06 20:45 UTC, Jellyfrog commented
You're adding a new database field but no sh schema migration created for it.
But I'm not so sure we should add this field since it seems we can just calculate it on the fly

2021-03-06 20:46 UTC, Jellyfrog requested changes
You're adding a new database field but no sh schema migration created for it.
But I'm not so sure we should add this field since it seems we can just calculate it on the fly

2021-03-07 21:13 UTC, Channing-Jiang commented
@Jellyfrog Yes, with this new database field, I am able to get the readable VLAN value for not only the encapsulation display but also the sap graph title and the API.

I am ok to just use the function to calculate it and function to reverse calculate the value, but it means that we need to run the functions all the time.

2021-03-07 21:37 UTC, craig-nokia commented
Let me know when you want me to test.  I have around 175 devices with ~2500 SAPs.   IMHO, using the database field would be faster.  But, who am I to know what is best.

2021-05-29 14:03 UTC, murrant commented
You need to rebase this and I agree that the display calculation is trivial and doesn't seem like it should add much to web page display.   We are generally more concerned about polling time than web loading time.  Polling usually happens more frequently.

2021-06-11 02:20 UTC, Channing-Jiang commented
@murrant Sorry, just saw this, so rebase those stuff without adding a new database field right?

2021-06-11 18:50 UTC, murrant commented
@Channing-Jiang I merged, so you don't need to rebase any more.  Just add the database migration.  (and probably still needs a review after that)

2021-11-02 22:57 UTC, Jellyfrog commented
First of all, thank you for your contribution!

We're closing this due to inactivity, feel free to reopen if you find the time to continue on this!

2021-11-02 22:57 UTC, closed without merging