Update api_functions.inc.php
librenms/librenms pull request #12912
Opened 2021-05-22 20:41 UTC by baroninn

searching for syslog message ;-)

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2021-05-22 20:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=12912) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=12912) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=12912) it.</sub>

2021-05-24 00:31 UTC, murrant requested changes
This allows SQL injection.  Need to use parameters.

2021-05-24 11:20 UTC, baroninn commented
@murrant
i'm no SQL injection specialist,,,, but i'm just doing the same as in other functions.. for example in "list_devices" function LINE: 307
how is my approach different ?
again: i'm just a novice programmer...
maybe you can help me understand what I need to change to prevent the SQL injection ?
since this is a very much needed functionality for my operations ;-)

thanks.

2021-05-24 21:53 UTC, nightcore500 commented
@baroninn 
You embed the content of the variable "msg" directly to the "query" variable. This allows SQL injections.
Use the placeholder "?" instead of the "msg" variable. (See also "prepared statements")

Like this (I have not checked the SQL query for correctness):
```
    $msg = $request->get('msg');
    if ($msg) {
        $query .= ' AND `msg` LIKE ?';
        $param[] = $msg;
    }
```

2021-06-15 00:43 UTC, murrant commented on includes/html/api_functions.inc.php
> +        $query .= " AND `msg` LIKE '%" . $msg . "%'";
The $param part below is correct, just use this for the query.
``` $query .= " AND `msg` LIKE '%?%'";```

This also needs a small documentation update so users know it exists.

2021-08-21 05:01 UTC, murrant commented
Closing due to inactivity, feel free to reopen.

2021-08-21 05:01 UTC, closed without merging