Rename nobulk -> snmp_bulk
librenms/librenms pull request #13098
Opened 2021-08-03 21:27 UTC by Jellyfrog

Rename option to align with the rest

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2021-08-03 21:29 UTC, Jellyfrog commented
Please note it switches from negative to positive option

2021-08-03 21:38 UTC, PipoCanaja commented
Hi @Jellyfrog 
Shouldn't we add a notification to this change?

2021-08-03 23:29 UTC, Jellyfrog commented
Doubt it's needed

2021-08-06 07:01 UTC, murrant commented on includes/snmp.inc.php
> +    if ($device['snmpver'] == 'v1' || (isset($device['os']) && Config::getOsSetting($device['os'], 'snmp_walk', true) == false)) {
snmp_walk  --> snmp_bulk

2021-08-06 07:08 UTC, murrant requested changes
fix typo ;)

2021-08-06 08:24 UTC, Jellyfrog commented on includes/snmp.inc.php
> +    if ($device['snmpver'] == 'v1' || (isset($device['os']) && Config::getOsSetting($device['os'], 'snmp_walk', true) == false)) {
Argh. How did I manage that...

2021-08-07 14:45 UTC, murrant commented
We probably do need a notification or backwards compatibility.   This is a likely option for people to set in their local config for problem devices.

2021-08-19 15:39 UTC, Jellyfrog commented
Hmm I see.

Well dont know if we should do it with the deprecated-config function thingy. because we need to loop all OSs...

Notification might be enough? :)

2021-08-19 18:47 UTC, murrant commented
Yep, fine with just a notification.  You can add it to the in-tree rss or the one on the web site.

2021-09-02 00:01 UTC, murrant approved these changes

2021-09-02 00:01 UTC, merged