Added initial IPv6 Address discovery for TP-LINK Jetstream
librenms/librenms pull request #13484
Opened 2021-11-08 10:17 UTC by Npeca75

TP-LINK using nonstandard approach for exposing IPv6 addresses on SNMP
so Jetstream switches was discovered without IPv6 addressess

![lnms1](https://user-images.githubusercontent.com/59750439/140724492-6e283108-82e5-47ca-9027-427dd70c392b.png)
added proper MIB file and logic in "includes/discovery/ipv6-addresses.inc.php"

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2021-11-08 10:41 UTC, Npeca75 commented
this is how TP-LINK handle IPv6 addresses

<code>
ipv6ParaConfigIfIndex.1.ipv6.autoIp.*.*.*.* = 1
ipv6ParaConfigIfIndex.1.ipv6.assignedEUI64Ip.*.*.*.* = 1
ipv6ParaConfigIfIndex.254.ipv6.autoIp.*.*.*.* = 254
ipv6ParaConfigIfIndex.254.ipv6.assignedEUI64Ip.*.*.*.* = 254
ipv6ParaConfigIfIndex.254.ipv6.assignedEUI64Ip.*.*.*.* = 254
ipv6ParaConfigIfDescription.1.ipv6.autoIp.*.*.*.* = VLAN1
ipv6ParaConfigIfDescription.1.ipv6.assignedEUI64Ip.*.*.*.* = VLAN1
ipv6ParaConfigIfDescription.254.ipv6.autoIp.*.*.*.* = VLAN254
ipv6ParaConfigIfDescription.254.ipv6.assignedEUI64Ip.*.*.*.* = VLAN254
ipv6ParaConfigIfDescription.254.ipv6.assignedEUI64Ip.*.*.*.* = VLAN254
ipv6ParaConfigAddrType.1.ipv6.autoIp.*.*.*.* = ipv6
ipv6ParaConfigAddrType.1.ipv6.assignedEUI64Ip.*.*.*.* = ipv6
ipv6ParaConfigAddrType.254.ipv6.autoIp.*.*.*.* = ipv6
ipv6ParaConfigAddrType.254.ipv6.assignedEUI64Ip.*.*.*.* = ipv6
ipv6ParaConfigAddrType.254.ipv6.assignedEUI64Ip.*.*.*.* = ipv6
ipv6ParaConfigAddress.1.ipv6.autoIp.*.*.*.* = "FE 80 00 00 00 00 00 00 76 DA 88 FF FE 68 2A D2 "
ipv6ParaConfigAddress.1.ipv6.assignedEUI64Ip.*.*.*.* = "FD 00 00 01 00 01 00 00 76 DA 88 FF FE 68 2A D2 "
ipv6ParaConfigAddress.254.ipv6.autoIp.*.*.*.* = "FE 80 00 00 00 00 00 00 76 DA 88 FF FE 68 2A D2 "
ipv6ParaConfigAddress.254.ipv6.assignedEUI64Ip.*.*.*.* = "3F FF 00 00 00 00 00 00 76 DA 88 FF FE 68 2A D2 "
ipv6ParaConfigAddress.254.ipv6.assignedEUI64Ip.*.*.*.* = "FD 00 00 01 02 54 00 00 76 DA 88 FF FE 68 2A D2 "
ipv6ParaConfigPrefixLength.1.ipv6.autoIp.*.*.*.* = 64
ipv6ParaConfigPrefixLength.1.ipv6.assignedEUI64Ip.*.*.*.* = 64
ipv6ParaConfigPrefixLength.254.ipv6.autoIp.*.*.*.* = 64
ipv6ParaConfigPrefixLength.254.ipv6.assignedEUI64Ip.*.*.*.* = 64
ipv6ParaConfigPrefixLength.254.ipv6.assignedEUI64Ip.*.*.*.* = 64
ipv6ParaConfigSourceType.1.ipv6.autoIp.*.*.*.* = autoIp
ipv6ParaConfigSourceType.1.ipv6.assignedEUI64Ip.*.*.*.* = assignedEUI64Ip
ipv6ParaConfigSourceType.254.ipv6.autoIp.*.*.*.* = autoIp
ipv6ParaConfigSourceType.254.ipv6.assignedEUI64Ip.*.*.*.* = assignedEUI64Ip
ipv6ParaConfigSourceType.254.ipv6.assignedEUI64Ip.*.*.*.* = assignedEUI64Ip
ipv6ParaConfigRowStatus.1.ipv6.autoIp.*.*.*.* = active
ipv6ParaConfigRowStatus.1.ipv6.assignedEUI64Ip.*.*.*.* = active
ipv6ParaConfigRowStatus.254.ipv6.autoIp.*.*.*.* = active
ipv6ParaConfigRowStatus.254.ipv6.assignedEUI64Ip.*.*.*.* = active
ipv6ParaConfigRowStatus.254.ipv6.assignedEUI64Ip.*.*.*.* = active
</code>

2021-11-08 13:58 UTC, murrant requested changes
Please split the os specific code out into another file like arp-table does.

2021-11-08 16:47 UTC, Npeca75 commented
> Please split the os specific code out into another file like arp-table does.

hi @murrant 
yes, you are right. it is much cleaner that way. Done

2021-11-09 19:39 UTC, Jellyfrog approved these changes

2021-11-09 19:40 UTC, merged