Oxidized reload Nodes when add device
librenms/librenms pull request #13728
Opened 2022-01-28 17:46 UTC by Jimmyord

Fix automatic Oxidized reload when adding device. Function got called when deleting device only.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2022-01-28 17:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=13728) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=13728) before we can accept your contribution.<br/><hr/>**jordonneau** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=13728) it.</sub>

2022-01-28 18:12 UTC, murrant requested changes
There is a much better place for this.

https://github.com/librenms/librenms/blob/master/app/Observers/DeviceObserver.php#L18

2022-01-28 18:24 UTC, Jimmyord commented
Should we move the same function call from include/functions.php to DeviceObserver (deleting function)?

2022-01-29 06:30 UTC, murrant commented
@Jimmyord Great! Exactly what is needed.  But I realized that not all places that call the code include the functions.inc.php file that has oxidized_reload_nodes().  This means we need to move it from there to a class that can be dynamically included.

That was not a small task and snowballed a bit so I made a new PR here #13730 

Thanks! without your PR that other one would not have been written.  Look forward to your next PR :)

2022-01-29 06:30 UTC, closed without merging