Misc webui code cleanups
librenms/librenms pull request #14242
Opened 2022-08-25 01:50 UTC by murrant

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2022-08-25 08:02 UTC, Jellyfrog requested changes

2022-08-25 08:02 UTC, Jellyfrog commented on includes/html/pages/device/port.inc.php
> +$port = \App\Models\Port::find($vars['port']);
This will not work since it gets inherited into all `includes/html/pages/device/port/*.inc.php` files ?

2022-08-29 13:38 UTC, Jellyfrog approved these changes

2022-08-30 17:55 UTC, merged

2022-08-31 18:20 UTC, allenacevedo commented
The 'allow_unauth_graphs' stopped working with this build.  We get a white box with "port*bits" in it.

Here is what i have in my config.php:
# unauth Graphs
$config['allow_unauth_graphs'] = true;
$config['allow_unauth_graphs_cidr'] = array('172.20.0.0/16');

2022-10-14 06:46 UTC, n-lyakhovoy commented
Hello, at this commit there is no information about port number and neighbour ip on device->ports view (last column);


https://github.com/librenms/librenms/commit/6f5cf7727a36e1bf0fca6be7779973fe82b4efad#r86757710

If i rollback string to `(strpos($port['label'], 'oopback') === false && ! $graph_type)` - neigbour ip/port information restores too