Fix reference to Rule ID
librenms/librenms pull request #14344
Opened 2022-09-13 08:03 UTC by ciroiriarte

Documentation makes reference to $alert->rule which is actually empty. $alert->rule_id on the other hand is actually populated.

Unsure if this came from a change, or it never worked. Documenting here so people don't chase ghost variables.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2022-09-13 08:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=14344) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=14344) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=14344) it.</sub>

2022-09-13 10:16 UTC, Jellyfrog commented
I think this requires some more investigation.
Also, there are more places in the code referring to it still.

2022-09-13 12:11 UTC, murrant commented on doc/Alerting/Templates.md
> -- Rule: `$alert->rule`
I think ->rule is supposed to be the rule name

2022-09-15 03:11 UTC, ciroiriarte commented
> I think this requires some more investigation. Also, there are more places in the code referring to it still.

Well, PR is for template expansion documentation only. Currently the documentation is not accurate

2022-09-15 04:38 UTC, murrant commented
Which is wrong though? The documentation or the code?

2022-09-16 19:11 UTC, PipoCanaja commented
Hi @ciroiriarte 
rule and rule_id are 2 different variables, containing 2 different values : 

```
    [rule] => %macros.device_down = "1"  
    [rule_id] => 1
    [name] => Devices up/down
```

`rule` is the rule itself, basically the conditions you created in the GUI
`rule_id`is the ID, in DB, of the rule. 

So what is necessary is probably a better explanation of which variable shows what.

2022-09-18 05:59 UTC, murrant commented
OHHHHH, rule is the legacy rule.  For almost all recently created rules the rule definition is in the builder, hence why the rule field is empty.

Thanks @PipoCanaja

2022-09-18 17:59 UTC, PipoCanaja commented
> OHHHHH, rule is the legacy rule. For almost all recently created rules the rule definition is in the builder field, hence why the rule field is empty.
> 
> Thanks @PipoCanaja

Got it. My "device up/down" rule on the test VM is old then :D 

@ciroiriarte You should probably remove `rule_id`and `rule` from the templates. ID by itself means nothing, unless used to create a link to the rule.

2022-09-18 18:07 UTC, PipoCanaja requested changes

2022-09-18 18:07 UTC, PipoCanaja commented on doc/Alerting/Templates.md
> +- Rule: `$alert->rule_id`
`- Rule ID: ``$alert->rule_id`` `

2022-09-18 18:07 UTC, PipoCanaja commented on doc/Alerting/Templates.md
> +Rule: @if ($alert->name) {{ $alert->name }} @else {{ $alert->rule_id }} @endif
you can keep only `$alert->name` instead of the `@if @else`

2022-09-18 18:07 UTC, PipoCanaja commented on doc/Alerting/Templates.md
> +Rule: @if ($alert->name) {{ $alert->name }} @else {{ $alert->rule_id }} @endif
same

2022-09-18 18:07 UTC, PipoCanaja commented on doc/Alerting/Templates.md
> +Rule: {{ $alert->name ?? $alert->rule_id }}
same

2022-09-18 18:07 UTC, PipoCanaja commented on doc/Alerting/Templates.md
> +Rule: @if ($alert->name) {{ $alert->name }} @else {{ $alert->rule_id }} @endif
same

2022-09-18 18:07 UTC, PipoCanaja commented on doc/Alerting/Templates.md
> +Rule: @if ($alert->name) {{ $alert->name }} @else {{ $alert->rule_id }} @endif <br>
same

2022-09-18 18:07 UTC, PipoCanaja commented on doc/Alerting/Templates.md
> +                    "value": "[{{ $alert->rule_id }}](https://your.librenms.url/device/device={{ $alert->device_id }}/tab=alert/)"
you could create a link to the rule instead

2022-10-02 18:05 UTC, PipoCanaja commented
Hi @ciroiriarte 
You can probably close this PR now. The rule is now properly filled both with legacy and modern rules. 
Bye

2022-10-11 18:50 UTC, murrant commented
Closing, as we resolved this another way.

2022-10-11 18:50 UTC, closed without merging

2022-10-11 19:26 UTC, ciroiriarte commented
> 

yup, use case for rule_id is for correlation in external platform. (northbound interface)