inital commit of a new syslog sink over http
librenms/librenms pull request #14424
Opened 2022-10-04 16:39 UTC by Bierchermuesli

This is an attempt of another way how LibreNMS can receive syslog messages. The difference and benefits to the [already known variant ](https://docs.librenms.org/Extensions/Syslog/#logstash) are the follow:

- better / easier integration in existing (complex) Logstash/Elastic setups
- no libreNMS components on Logstash server necessary
- Logstash and LibreNMS hosts can be different network zones
- Logstash can buffer and submit multiple syslogs in one HTTP POST
- http as lightweight protocol for transport over WAN
- reverse proxy/load sharing as option
- easy scale out options on LibreNMS side
- firewall / WAF friendly
- http auth, SSL etc (available on logstash side)
- ....? 

Sample schema:
```
  ┌──────┐
  │Device├─►┌───────────────────┐                ┌──────────────┐
  └──────┘  │Logstash Cluster   ├┬──────────────►│ElasticSearch ├┐
            │  RabbitMQ         ││               │ Cluster      ││
 ┌──────┬──►│    Filtering etc  ││ ───────┐      └┬─────────────┼│
 │Device│   └┬──────────────────┼│        │       └──────────────┘
 └──────┘    └───────────────────┘        ▼
                                      ~~~WAN~~~
                                          │
                                        ┌─┼─┐
                                        │┼┼┼│ LB / Firewall
                                        └─┼─┘
                                          │
                                          ▼
                         ┌────────────────────┐    ┌────────────────────┐
                         │LibreNMS Sink       ├┬──►│LibreNMS Master     │
                         │syslog-http-sink.php││   │ MariaDB            │
                         └┬───────────────────┼│   └────────────────────┘
                          └────────────────────┘
```
Minimal [Logstash](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-http.html) config
```
     output {
     ....
     		#feed it to LibreNMS
     		http {
     						http_method => "post"
     						url => "http://sink1.nts.ch/syslog-http-sink.php"
     						format => "json_batch"
     		}
}
```
Further toughs:
- For performance and simplify I decide to leave this 'module' standalone instead of the common LibreNMS API. 
- File location: The LibreNMS root `/` where `syslog.php` resides might be a better choice  (nginx alias?). Please advice
- A proper documentation in https://docs.librenms.org/Extensions/Syslog/ can be made
- Idea for further improvement:
  - deadman detection
  - statistics / graphs
  - stats / json output
  - authentication as default (default security enabled)
  - no plain html / document output if GET is used

-> Thanks for any advice or inputs for better contributing

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2022-10-04 16:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=14424) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=14424) before we can accept your contribution.<br/><hr/>**Bierchermüesli** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=14424) it.</sub>

2022-10-25 21:23 UTC, murrant commented
Seems decent, but why ingest the logs into LibreNMS?

Elastic search is a superior form of storage for logs.  I would much rather see something similar to how Graylog works.

2022-10-25 21:44 UTC, Bierchermuesli commented
1. centralized Alarm triggers 
   - often some Events are not handled by trap or visible trough polling. 
   - e.g. Authentication failure, Maxprefix, Severy-x in n-time,  etc.. - already available in the Alert rule collection
2. centralizing of information
   - side by side/coloration with Outages, Event Log, Syslog, Traps etc..
   - good for a quick view for simple NOC staff
 
Indeed Kibana/Grafana/Graylog can do it better. IMHO libreNMS do it all right for a simple view and we have everything in one tool.

In my case I  use external link for Kibana for long term or aggregation searches. I would set a short libreNMS log retention. Also with (my) ELK stack there is no alert handling - graylog would be an option but centraliced alert rule handling is a plus.

2022-11-07 19:41 UTC, murrant commented
Sorry for the slow review. Reasoning seems sound.

This should be part of the API.  Current code allows unauthenticated database injection.
We do not allow any new legacy pages to be added.  All need be defined in the routes files.

Let me know if you need any further help/guidance.  Again, thanks for your submission.

2022-11-11 03:27 UTC, murrant requested changes
Move to API

2022-11-11 15:14 UTC, Bierchermuesli commented
Thanks for the reply. I can understand the API thing but this adds some extra overhead.

Can you point me some API examples or similar existing use cases where I can try to adapt?

2022-12-05 22:31 UTC, Bierchermuesli commented
Soo... I did some home work and I hopefully integrated this feature well into the libreNMS API. Comment above is updated with curl test data. let me know what you think .

2022-12-16 02:14 UTC, murrant commented
Looks more reasonable.  Could use a refinement pass.

The main thing missing is documentation :)

2022-12-16 02:16 UTC, murrant commented on includes/html/api_functions.inc.php
> +    $json = json_decode($request->getContent(), true);
```suggestion
    $json = $request->json();
```

2022-12-16 02:18 UTC, murrant commented on includes/html/api_functions.inc.php
> +    $json = json_decode($request->getContent(), true);
then below, you only need the loop:
```php
        foreach ($logs as $entry) {
            process_syslog($entry, 1);
        }
```

2022-12-16 15:47 UTC, murrant commented on includes/html/api_functions.inc.php
> +    return api_success_noresult(200, 'Syslog recived: ' . count($json));
```suggestion
    return api_success_noresult(200, 'Syslog received: ' . count($logs));
```

2023-03-06 10:08 UTC, Bierchermuesli commented
@murrant  documentation is done. I tried to re-org the syslog page a bit. let me know what you think or what it is missing.

2023-03-15 13:14 UTC, murrant approved these changes
LGTM

2023-03-15 13:14 UTC, merged