Add download button to device config page
librenms/librenms pull request #14709
Opened 2022-12-07 21:34 UTC by gazpachoking

Adds a button to the device configuration page to download the viewed config version from oxidized.

On modern browsers this will just open the raw config in a new tab, since the 'download' attribute on the link doesn't apply for security reasons when linking to another domain. This could be fixed by adding an endpoint to librenms to proxy the raw config, but it didn't seem worth it since you can just right click the link and do a save as, or save from the resulting tab.

This also fixes a small bug where the version number passed in oxidized url parameters was always equal to the maximum version number. Seems oxidized ignored this argument though, so it doesn't matter much.

Feature request here:
https://community.librenms.org/t/oxidized-configuration-download-button/11780

![image](https://user-images.githubusercontent.com/187133/206299142-6b679e40-e68b-4cc5-8b66-a4fa904c3aad.png)

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2022-12-07 21:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=14709) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=14709) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=14709) it.</sub>

2022-12-07 22:16 UTC, gazpachoking commented
> I like the idea. However, I have a problem with it linking directly to the Oxidized URI.
> 
> For security reasons, we have our Oxidized segregated from the rest of our network, and the only way to access it is through a secure jumphost or through the pin hole, allowing API requests only from Libre. Imagine how big of a problem it would be if your Oxidized server got compromised? Copy of all the configs and access to the equipment.
> 
> The download request should be proxied through Libre.

Yeah, that would be nicer for other reasons as well, including making the download link actually download the file, and letting us provide a filename hint. I'm not super familiar with the codebase though, do you know where that proxying should occur?

2022-12-07 22:25 UTC, electrocret commented
The API does a proxying like function already, you could likely copy it.
https://github.com/librenms/librenms/blob/fbd4bc126973b394a17a7efcdf04d306411f1fd0/includes/html/api_functions.inc.php#L1434

2022-12-07 22:53 UTC, gazpachoking commented
Just found that as well. Upgrading that endpoint to allow requesting a specific versions seems like a good plan. I'm not sure how I call that api endpoint from the webui though.. I'll keep digging.

Another note, what is securing your oxidized instance that this method would open up? If I add an endpoint that proxies the oxidized config, how would that be, (or rather, how would I ensure that it is,) more secure?

2022-12-08 23:06 UTC, ottorei commented
> The API does a proxying like function already, you could likely use it for reference.
> 
> https://github.com/librenms/librenms/blob/fbd4bc126973b394a17a7efcdf04d306411f1fd0/includes/html/api_functions.inc.php#L1434

I agree that the proper way to achieve this download feature is to load the specified configuration file through Oxidized API using NMS itself just like the existing configuration fetching does. With direct access the default configuration would not even authenticate users and this would possibly pose a security issue. Also, using NMS server to fetch the configs, there would be no need for any routing between the http client and the Oxidized server unless one explicitly wishes to do so.

2022-12-08 23:25 UTC, ottorei requested changes
Please check the existing Oxidized API access code and try to convert this feature to use connectivity of the NMS server to the Oxidixed instead of direct access from web clients.

2023-01-20 19:48 UTC, PipoCanaja commented
> Another note, what is securing your oxidized instance that this method would open up? If I add an endpoint that proxies the oxidized config, how would that be, (or rather, how would I ensure that it is,) more secure?

In fact, it is as secure as LibreNMS is. But as Oxidized GUI is minimalist, a few of us prefer to keep it locked on 127.0.0.1 and only access it thru LibreNMS. So any direct link to it would not even work in that case. 
Using the proxy function is indeed the only way to ensure that the download button will work for all, and that the security will remain as "good" as it currently is.

2024-01-09 22:26 UTC, PipoCanaja commented
Hi @gazpachoking 
Are you still working on this PR ?
Thanx

2024-10-03 02:28 UTC, murrant commented
Thanks for your pull request. You haven't updated this PR in some time. Closing it for now.

Please feel free to reopen, I would love to see your changes added to LibreNMS.

2024-10-03 02:28 UTC, closed without merging