implement LINE Messaging API
librenms/librenms pull request #14802
Opened 2023-01-23 02:24 UTC by j796160836

[LINE](https://line.me) is a messanger aim for Asia users.

It provide an API for developers to send message to users or groups.
[Documentation](https://developers.line.biz/en/docs/messaging-api/overview/)

I also add setup instructions in `Alerting/Transports.md`.

Note that, LINE notify and LINE Messaging API are different services.

----

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2023-01-23 02:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=14802) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=14802) before we can accept your contribution.<br/><hr/>**Johnny** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=14802) it.</sub>

2023-01-24 10:43 UTC, nomadbard916 commented on LibreNMS/Alert/Transport/LineMessagingAPI.php
> +        curl_close($curl);
why not just use guzzle when there's already dependency in composer.json

2023-02-01 16:10 UTC, murrant commented
I've just been working on a cleanup of all of the alert transports.  Because this copies code from existing transports, it needs to be cleaned up as well. See #14763

2023-02-06 06:24 UTC, j796160836 commented
Got it. Applied clean up at `apply_cleanup` branch.
Take a look: https://github.com/j796160836/librenms/tree/apply_cleanup

2023-02-20 08:23 UTC, j796160836 commented
Here is realtime alert screenshot
<img width="223" alt="Screenshot 2023-02-20 at 4 19 30 PM" src="https://user-images.githubusercontent.com/686478/220051244-7b0eb880-ee74-495c-be8f-7c4f78ff89f7.png">

2023-02-28 23:31 UTC, Jellyfrog requested changes
Blocked by #14763

2023-07-07 13:57 UTC, murrant commented
@j796160836 Thanks, now that the other PRs have been merged, you will need to update your code to match their style.

2023-08-04 16:05 UTC, murrant commented
Merging #14867

2023-08-04 16:05 UTC, closed without merging