Fix poller service early process logging
librenms/librenms pull request #14830
Opened 2023-02-04 16:01 UTC by TheMysteriousX

A previous code cleanup moved these parameters into an 'if' block, but didn't account for the order they needed to be in to function.

This change re-orders the parameters so they work as intended again.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2023-02-09 08:59 UTC, ottorei reviewed
Code looks good to me. Did you test the possible config combinations with and without debugging?

2023-02-13 12:53 UTC, ottorei approved these changes

2023-02-14 15:12 UTC, ottorei commented
There seems to be an issue if the log level was not set. Just tested this on my system and the service is no longer starting.

`Feb 14 17:11:05 nms-poller-01 librenms-service.py[3471948]: MainThread(INFO):Initial log level was set to INFO
Feb 14 17:11:05 nms-poller-01 librenms-service.py[3471948]: MainThread(INFO):Configuring LibreNMS service
Feb 14 17:11:05 nms-poller-01 librenms-service.py[3471948]: MainThread(INFO):Attempting to load .env from '/opt/librenms/.env'
Feb 14 17:11:05 nms-poller-01 librenms-service.py[3471948]: 'ServiceConfig' object has no attribute 'poller_log_level'
Feb 14 17:11:06 nms-poller-01 systemd[1]: librenms.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 14 17:11:06 nms-poller-01 systemd[1]: librenms.service: Failed with result 'exit-code'.
`

2023-02-14 15:45 UTC, ottorei requested changes
I was having trouble starting multiple pollers with these changes in place. It seems that the `poller_log_level` can be accessed before it is defined.

2023-02-14 20:38 UTC, TheMysteriousX commented
Ah, that's my bad - that line works as expected if this was ansible :)

I'll fix it.

2024-12-08 18:43 UTC, PipoCanaja commented
Hi @TheMysteriousX 
As this PR seems to be stalled, we'll close it for now. Whenever you have time to continue it, feel free to re-open.
Thanx

2024-12-08 18:43 UTC, closed without merging