Add support for older Geist/ITWatchdog relaygoose
librenms/librenms pull request #14971
Opened 2023-04-16 13:27 UTC by Moonlight63

Add support for older Geist/ITWatchdog relaygoose

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2023-04-16 13:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=14971) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=14971) before we can accept your contribution.<br/><hr/>**Dalen Catt** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=14971) it.</sub>

2023-04-21 00:02 UTC, Moonlight63 commented
I don't know how to make it recheck the CLA. I signed it, but it didn't work.

2023-04-25 12:49 UTC, murrant commented
@Moonlight63 sorry, the CLA script doesn't work if your github email and commit email don't match.

2023-04-25 12:51 UTC, murrant commented
Also, your sensors should be defined in yaml if possible.

2023-04-25 13:52 UTC, Moonlight63 commented
Oh, OK, I guess I entered a different email? My bad. As for the sensors, I just copied the format that already existed for the sensors that matched the closest. I did define the discovery in yaml if that's what you are talking about. Otherwise I don't exactly know what I'm doing, I just needed it to work, and this was the only way it seemed to work. If I got rid of the php files then none of the sensors were being scanned.

2024-04-01 09:46 UTC, PipoCanaja requested changes

2024-04-01 09:46 UTC, PipoCanaja commented on includes/discovery/sensors/airflow/wxgoos.inc.php
> +}
Hi @Moonlight63 
This one can be converted into YAML.

2024-04-01 09:46 UTC, PipoCanaja commented on includes/discovery/sensors/temperature/wxgoos.inc.php
> +<?php
This file can also easily migrate to YAML

2024-04-01 09:46 UTC, PipoCanaja commented on includes/polling/sensors/pre-cache/wxgoos.php
> +<?php
Same

2024-04-01 09:46 UTC, PipoCanaja commented on includes/polling/sensors/temperature/wxgoos.php
> +<?php
Same

2024-12-08 18:25 UTC, PipoCanaja commented
Hi @Moonlight63 
As this PR seems to be stalled, we'll close it for now. Whenever you have time to continue it, feel free to re-open.
Thanx

2024-12-08 18:25 UTC, closed without merging