add feature to read ports and VRFs for AOS7 devices
librenms/librenms pull request #15638
Opened 2023-12-14 11:57 UTC by tbk2

Please give a short description what your pull request is for

This pull request introduces enhancements to SNMP context handling, specifically adding support for Alcatel AOS7 devices and a new optional SNMP options parameter in the NetSnmpQuery class.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2023-12-14 11:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=15638) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=15638) before we can accept your contribution.<br/><hr/>**Tamas Baumgartner-Kis** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=15638) it.</sub>

2023-12-15 23:21 UTC, PipoCanaja requested changes

2023-12-15 23:21 UTC, PipoCanaja commented on phpstan-baseline-deprecated.neon
> +			count: 10
Hello,
This is not the goal to increase these values :D Of course, lowering them is allowed :) you can mix eloquent requests in an existing file (and keep count==6, or even better, change some DbFacile requests to eloquent and lower this value)

2023-12-15 23:23 UTC, PipoCanaja commented
Hi @tbk2 
Thanx for your PR and welcome in the project. Could you write your DB requests in Eloquent mode instead of DbFacile ? And of course, ask for help if needed. The community is trying to get rid of DbFacile and adding new lines of code using it is not helping us to reach that goal :) 
Thanx

2024-04-25 19:34 UTC, paulierco commented
@tbk2  Do you want support with this?

2025-03-20 23:10 UTC, laf commented
Closing for now until updates provided. We can then re-open the pull request.

2025-03-20 23:10 UTC, closed without merging