Powervault ME Sensors
librenms/librenms pull request #15814
Opened 2024-02-10 04:49 UTC by TheMysteriousX

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-02-10 10:35 UTC, PipoCanaja commented
Hi @TheMysteriousX 
For all polling PHP code, you need to ensure that your are only changing the OIDs that your are expecting to change. If not, your code will apply for each and every OIDs that are currently polled. or will later be added.
Thx

2024-02-10 16:12 UTC, Jellyfrog commented
Any reason this can't be done in yaml?

2024-02-10 16:48 UTC, TheMysteriousX commented
You have to know in advance what type of sensor is at an OID to use YAML. The sensors presented are not tabulated - you have to poll it, then parse it to see what type of sensor you got.

2024-03-08 01:46 UTC, TheMysteriousX commented
This is good to go, thought there was an issue with discovery but it's down to a database column being too small.
I'll address that seperately.

2024-05-08 04:00 UTC, murrant requested changes
99% sure this can be in yaml.
You use skip_values to reject everything not of the type for that sensor.

2024-05-08 08:07 UTC, TheMysteriousX commented
I'm going to need an example because I've found no documented way to parse descriptions with YAML.

2024-05-12 01:46 UTC, TheMysteriousX commented
I've tested it with skip values as you suggested, and on every poll there is a sensor update message logged for every single sensor as the sensor description changes.

Unless I've missed something, there's no support in simple template for what you're asking me to do:
  https://github.com/librenms/librenms/blob/master/app/View/SimpleTemplate.php

All it supports are simple substitutions.

2024-05-16 02:51 UTC, murrant commented
Wouldn't this work?
```yaml
        current:
            data:
                -
                    oid: FCMGMT-MIB::connUnitSensorTable
                    value: FCMGMT-MIB::connUnitSensorMessage
                    num_oid: '.1.3.6.1.3.94.1.8.1.6.{{ $index }}'
                    descr: FCMGMT-MIB::connUnitSensorName
                    skip_values:
                        -
                            oid: FCMGMT-MIB::connUnitSensorCharacteristic
                            op: '!='
                            value: 6 # might be currentValue instead
```

2024-05-20 22:59 UTC, adam-bishop commented
The device does not produce a value that is valid for YAML. You can't graph "24-port Expander, Right Sideplane: 43 C 109.40F".

Your example is essentially what I did, but it doesn't work due to the values needing to be parsed.

```
.*.*.*.*.*.*.0.0.1 = 1
.*.*.*.*.*.*.0.0.2 = 2
.*.*.*.*.*.*.0.0.3 = 3
.*.*.*.*.*.*.0.0.4 = 4
.*.*.*.*.*.*.0.0.5 = 5
.*.*.*.*.*.*.0.0.6 = 6
.*.*.*.*.*.*.0.0.7 = 7
.*.*.*.*.*.*.0.0.8 = 8
.*.*.*.*.*.*.0.0.9 = 9
.*.*.*.*.*.*.0.0.10 = 10
.*.*.*.*.*.*.0.0.11 = 11
.*.*.*.*.*.*.0.0.12 = 12
.*.*.*.*.*.*.0.0.13 = 13
.*.*.*.*.*.*.0.0.14 = 14
.*.*.*.*.*.*.0.0.15 = 15
.*.*.*.*.*.*.0.0.16 = 16
.*.*.*.*.*.*.0.0.17 = 17
.*.*.*.*.*.*.0.0.18 = 18
.*.*.*.*.*.*.0.0.19 = 19
.*.*.*.*.*.*.0.0.20 = 20
.*.*.*.*.*.*.0.0.21 = 21
.*.*.*.*.*.*.0.0.22 = 22
.*.*.*.*.*.*.0.0.23 = 23
.*.*.*.*.*.*.0.0.24 = 24
.*.*.*.*.*.*.0.0.25 = 25
.*.*.*.*.*.*.0.0.26 = 26
.*.*.*.*.*.*.0.0.27 = 27
.*.*.*.*.*.*.0.0.28 = 28
.*.*.*.*.*.*.0.0.29 = 29
.*.*.*.*.*.*.0.0.30 = 30
.*.*.*.*.*.*.0.0.31 = 31
.*.*.*.*.*.*.0.0.32 = 32
.*.*.*.*.*.*.0.0.33 = 33
.*.*.*.*.*.*.0.0.34 = 34
.*.*.*.*.*.*.0.0.35 = 35
.*.*.*.*.*.*.0.0.36 = 36
.*.*.*.*.*.*.0.0.37 = 37
.*.*.*.*.*.*.0.0.38 = 38
.*.*.*.*.*.*.0.0.39 = 39
.*.*.*.*.*.*.0.0.40 = 40
.*.*.*.*.*.*.0.0.41 = 41
.*.*.*.*.*.*.0.0.42 = 42
.*.*.*.*.*.*.0.0.43 = 43
.*.*.*.*.*.*.0.0.44 = 44
.*.*.*.*.*.*.0.0.45 = 45
.*.*.*.*.*.*.0.0.46 = 46
.*.*.*.*.*.*.0.0.47 = 47
.*.*.*.*.*.*.0.0.48 = 48
.*.*.*.*.*.*.0.0.49 = 49
.*.*.*.*.*.*.0.0.50 = 50
.*.*.*.*.*.*.0.0.51 = 51
.*.*.*.*.*.*.0.0.52 = 52
.*.*.*.*.*.*.0.0.53 = 53
.*.*.*.*.*.*.0.0.54 = 54
.*.*.*.*.*.*.0.0.55 = 55
.*.*.*.*.*.*.0.0.56 = 56
.*.*.*.*.*.*.0.0.57 = 57
.*.*.*.*.*.*.0.0.1 = "CPU Temperature-Ctlr B"
.*.*.*.*.*.*.0.0.2 = "Capacitor Pack Temperature-Ctlr B"
.*.*.*.*.*.*.0.0.3 = "Expander Temperature-Ctlr B"
.*.*.*.*.*.*.0.0.4 = "Disk Controller Temperature-Ctlr B"
.*.*.*.*.*.*.0.0.5 = "Host Left IOC Temperature-Ctlr B"
.*.*.*.*.*.*.0.0.6 = "CPU Temperature-Ctlr A"
.*.*.*.*.*.*.0.0.7 = "Capacitor Pack Temperature-Ctlr A"
.*.*.*.*.*.*.0.0.8 = "Expander Temperature-Ctlr A"
.*.*.*.*.*.*.0.0.9 = "Disk Controller Temperature-Ctlr A"
.*.*.*.*.*.*.0.0.10 = "Host Left IOC Temperature-Ctlr A"
.*.*.*.*.*.*.0.0.11 = "Capacitor Pack Voltage-Ctlr B"
.*.*.*.*.*.*.0.0.12 = "Capacitor Cell 1 Voltage-Ctlr B"
.*.*.*.*.*.*.0.0.13 = "Capacitor Cell 2 Voltage-Ctlr B"
.*.*.*.*.*.*.0.0.14 = "Capacitor Cell 3 Voltage-Ctlr B"
.*.*.*.*.*.*.0.0.15 = "Capacitor Cell 4 Voltage-Ctlr B"
.*.*.*.*.*.*.0.0.16 = "Capacitor Pack Voltage-Ctlr A"
.*.*.*.*.*.*.0.0.17 = "Capacitor Cell 1 Voltage-Ctlr A"
.*.*.*.*.*.*.0.0.18 = "Capacitor Cell 2 Voltage-Ctlr A"
.*.*.*.*.*.*.0.0.19 = "Capacitor Cell 3 Voltage-Ctlr A"
.*.*.*.*.*.*.0.0.20 = "Capacitor Cell 4 Voltage-Ctlr A"
.*.*.*.*.*.*.0.0.21 = "Capacitor Charge-Ctlr B"
.*.*.*.*.*.*.0.0.22 = "Capacitor Charge-Ctlr A"
.*.*.*.*.*.*.0.0.23 = "Overall Unit Status"
.*.*.*.*.*.*.0.0.24 = "SBB IOM Inlet Temperature Loc: lower-IOM B"
.*.*.*.*.*.*.0.0.25 = "Expander Internal Temperature Loc: lower-IOM B"
.*.*.*.*.*.*.0.0.26 = "SBB IOM Inlet Temperature Loc: upper-IOM A"
.*.*.*.*.*.*.0.0.27 = "Expander Internal Temperature Loc: upper-IOM A"
.*.*.*.*.*.*.0.0.28 = "Temperature Inlet Loc: right-PSU"
.*.*.*.*.*.*.0.0.29 = "Temperature Hotspot Loc: right-PSU"
.*.*.*.*.*.*.0.0.30 = "Temperature Inlet Loc: left-PSU"
.*.*.*.*.*.*.0.0.31 = "Temperature Hotspot Loc: left-PSU"
.*.*.*.*.*.*.0.0.32 = "Front-Right Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.33 = "Middle-Left Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.34 = "Rear-Left Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.35 = "Rear-Right Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.36 = "Front-Right Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.37 = "Middle-Left Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.38 = "Rear-Left Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.39 = "Rear-Right Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.40 = "24-port Expander, Right Sideplane"
.*.*.*.*.*.*.0.0.41 = "36-port Expander, Right Sideplane"
.*.*.*.*.*.*.0.0.42 = "24-port Expander, Left Sideplane"
.*.*.*.*.*.*.0.0.43 = "36-port Expander, Left Sideplane"
.*.*.*.*.*.*.0.0.44 = "Ambient Temp, Left Sideplane"
.*.*.*.*.*.*.0.0.45 = "24-port Expander, Right Sideplane"
.*.*.*.*.*.*.0.0.46 = "36-port Expander, Right Sideplane"
.*.*.*.*.*.*.0.0.47 = "24-port Expander, Left Sideplane"
.*.*.*.*.*.*.0.0.48 = "36-port Expander, Left Sideplane"
.*.*.*.*.*.*.0.0.49 = "Ambient Temp, Left Sideplane"
.*.*.*.*.*.*.0.0.50 = "Voltage 12V Rail Loc: right-PSU"
.*.*.*.*.*.*.0.0.51 = "Voltage 5V Rail Loc: right-PSU"
.*.*.*.*.*.*.0.0.52 = "Voltage 12V Rail Loc: left-PSU"
.*.*.*.*.*.*.0.0.53 = "Voltage 5V Rail Loc: left-PSU"
.*.*.*.*.*.*.0.0.54 = "Current 12V Rail Loc: right-PSU"
.*.*.*.*.*.*.0.0.55 = "Current 5V Rail Loc: right-PSU"
.*.*.*.*.*.*.0.0.56 = "Current 12V Rail Loc: left-PSU"
.*.*.*.*.*.*.0.0.57 = "Current 5V Rail Loc: left-PSU"
.*.*.*.*.*.*.0.0.1 = 3
.*.*.*.*.*.*.0.0.2 = 3
.*.*.*.*.*.*.0.0.3 = 3
.*.*.*.*.*.*.0.0.4 = 3
.*.*.*.*.*.*.0.0.5 = 3
.*.*.*.*.*.*.0.0.6 = 3
.*.*.*.*.*.*.0.0.7 = 3
.*.*.*.*.*.*.0.0.8 = 3
.*.*.*.*.*.*.0.0.9 = 3
.*.*.*.*.*.*.0.0.10 = 3
.*.*.*.*.*.*.0.0.11 = 3
.*.*.*.*.*.*.0.0.12 = 3
.*.*.*.*.*.*.0.0.13 = 3
.*.*.*.*.*.*.0.0.14 = 3
.*.*.*.*.*.*.0.0.15 = 3
.*.*.*.*.*.*.0.0.16 = 3
.*.*.*.*.*.*.0.0.17 = 3
.*.*.*.*.*.*.0.0.18 = 3
.*.*.*.*.*.*.0.0.19 = 3
.*.*.*.*.*.*.0.0.20 = 3
.*.*.*.*.*.*.0.0.21 = 3
.*.*.*.*.*.*.0.0.22 = 3
.*.*.*.*.*.*.0.0.23 = 3
.*.*.*.*.*.*.0.0.24 = 3
.*.*.*.*.*.*.0.0.25 = 3
.*.*.*.*.*.*.0.0.26 = 3
.*.*.*.*.*.*.0.0.27 = 3
.*.*.*.*.*.*.0.0.28 = 3
.*.*.*.*.*.*.0.0.29 = 3
.*.*.*.*.*.*.0.0.30 = 3
.*.*.*.*.*.*.0.0.31 = 3
.*.*.*.*.*.*.0.0.32 = 3
.*.*.*.*.*.*.0.0.33 = 3
.*.*.*.*.*.*.0.0.34 = 3
.*.*.*.*.*.*.0.0.35 = 3
.*.*.*.*.*.*.0.0.36 = 3
.*.*.*.*.*.*.0.0.37 = 3
.*.*.*.*.*.*.0.0.38 = 3
.*.*.*.*.*.*.0.0.39 = 3
.*.*.*.*.*.*.0.0.40 = 3
.*.*.*.*.*.*.0.0.41 = 3
.*.*.*.*.*.*.0.0.42 = 3
.*.*.*.*.*.*.0.0.43 = 3
.*.*.*.*.*.*.0.0.44 = 3
.*.*.*.*.*.*.0.0.45 = 3
.*.*.*.*.*.*.0.0.46 = 3
.*.*.*.*.*.*.0.0.47 = 3
.*.*.*.*.*.*.0.0.48 = 3
.*.*.*.*.*.*.0.0.49 = 3
.*.*.*.*.*.*.0.0.50 = 3
.*.*.*.*.*.*.0.0.51 = 3
.*.*.*.*.*.*.0.0.52 = 3
.*.*.*.*.*.*.0.0.53 = 3
.*.*.*.*.*.*.0.0.54 = 3
.*.*.*.*.*.*.0.0.55 = 3
.*.*.*.*.*.*.0.0.56 = 3
.*.*.*.*.*.*.0.0.57 = 3
.*.*.*.*.*.*.0.0.1 = ""
.*.*.*.*.*.*.0.0.2 = ""
.*.*.*.*.*.*.0.0.3 = ""
.*.*.*.*.*.*.0.0.4 = ""
.*.*.*.*.*.*.0.0.5 = ""
.*.*.*.*.*.*.0.0.6 = ""
.*.*.*.*.*.*.0.0.7 = ""
.*.*.*.*.*.*.0.0.8 = ""
.*.*.*.*.*.*.0.0.9 = ""
.*.*.*.*.*.*.0.0.10 = ""
.*.*.*.*.*.*.0.0.11 = ""
.*.*.*.*.*.*.0.0.12 = ""
.*.*.*.*.*.*.0.0.13 = ""
.*.*.*.*.*.*.0.0.14 = ""
.*.*.*.*.*.*.0.0.15 = ""
.*.*.*.*.*.*.0.0.16 = ""
.*.*.*.*.*.*.0.0.17 = ""
.*.*.*.*.*.*.0.0.18 = ""
.*.*.*.*.*.*.0.0.19 = ""
.*.*.*.*.*.*.0.0.20 = ""
.*.*.*.*.*.*.0.0.21 = ""
.*.*.*.*.*.*.0.0.22 = ""
.*.*.*.*.*.*.0.0.23 = ""
.*.*.*.*.*.*.0.0.24 = ""
.*.*.*.*.*.*.0.0.25 = ""
.*.*.*.*.*.*.0.0.26 = ""
.*.*.*.*.*.*.0.0.27 = ""
.*.*.*.*.*.*.0.0.28 = ""
.*.*.*.*.*.*.0.0.29 = ""
.*.*.*.*.*.*.0.0.30 = ""
.*.*.*.*.*.*.0.0.31 = ""
.*.*.*.*.*.*.0.0.32 = ""
.*.*.*.*.*.*.0.0.33 = ""
.*.*.*.*.*.*.0.0.34 = ""
.*.*.*.*.*.*.0.0.35 = ""
.*.*.*.*.*.*.0.0.36 = ""
.*.*.*.*.*.*.0.0.37 = ""
.*.*.*.*.*.*.0.0.38 = ""
.*.*.*.*.*.*.0.0.39 = ""
.*.*.*.*.*.*.0.0.40 = ""
.*.*.*.*.*.*.0.0.41 = ""
.*.*.*.*.*.*.0.0.42 = ""
.*.*.*.*.*.*.0.0.43 = ""
.*.*.*.*.*.*.0.0.44 = ""
.*.*.*.*.*.*.0.0.45 = ""
.*.*.*.*.*.*.0.0.46 = ""
.*.*.*.*.*.*.0.0.47 = ""
.*.*.*.*.*.*.0.0.48 = ""
.*.*.*.*.*.*.0.0.49 = ""
.*.*.*.*.*.*.0.0.50 = ""
.*.*.*.*.*.*.0.0.51 = ""
.*.*.*.*.*.*.0.0.52 = ""
.*.*.*.*.*.*.0.0.53 = ""
.*.*.*.*.*.*.0.0.54 = ""
.*.*.*.*.*.*.0.0.55 = ""
.*.*.*.*.*.*.0.0.56 = ""
.*.*.*.*.*.*.0.0.57 = ""
.*.*.*.*.*.*.0.0.1 = "CPU Temperature-Ctlr B: 60 C 140.00F"
.*.*.*.*.*.*.0.0.2 = "Capacitor Pack Temperature-Ctlr B: 37 C 98.60F"
.*.*.*.*.*.*.0.0.3 = "Expander Temperature-Ctlr B: 63 C 145.40F"
.*.*.*.*.*.*.0.0.4 = "Disk Controller Temperature-Ctlr B: 68 C 154.40F"
.*.*.*.*.*.*.0.0.5 = "Host Left IOC Temperature-Ctlr B: 51 C 123.80F"
.*.*. [...]

2024-05-20 23:00 UTC, TheMysteriousX commented
The device does not produce a value that is valid for YAML. You can't graph "24-port Expander, Right Sideplane: 43 C 109.40F".

Your example is essentially what I did, but it doesn't work due to the values needing to be parsed.

```
.*.*.*.*.*.*.0.0.1 = 1
.*.*.*.*.*.*.0.0.2 = 2
.*.*.*.*.*.*.0.0.3 = 3
.*.*.*.*.*.*.0.0.4 = 4
.*.*.*.*.*.*.0.0.5 = 5
.*.*.*.*.*.*.0.0.6 = 6
.*.*.*.*.*.*.0.0.7 = 7
.*.*.*.*.*.*.0.0.8 = 8
.*.*.*.*.*.*.0.0.9 = 9
.*.*.*.*.*.*.0.0.10 = 10
.*.*.*.*.*.*.0.0.11 = 11
.*.*.*.*.*.*.0.0.12 = 12
.*.*.*.*.*.*.0.0.13 = 13
.*.*.*.*.*.*.0.0.14 = 14
.*.*.*.*.*.*.0.0.15 = 15
.*.*.*.*.*.*.0.0.16 = 16
.*.*.*.*.*.*.0.0.17 = 17
.*.*.*.*.*.*.0.0.18 = 18
.*.*.*.*.*.*.0.0.19 = 19
.*.*.*.*.*.*.0.0.20 = 20
.*.*.*.*.*.*.0.0.21 = 21
.*.*.*.*.*.*.0.0.22 = 22
.*.*.*.*.*.*.0.0.23 = 23
.*.*.*.*.*.*.0.0.24 = 24
.*.*.*.*.*.*.0.0.25 = 25
.*.*.*.*.*.*.0.0.26 = 26
.*.*.*.*.*.*.0.0.27 = 27
.*.*.*.*.*.*.0.0.28 = 28
.*.*.*.*.*.*.0.0.29 = 29
.*.*.*.*.*.*.0.0.30 = 30
.*.*.*.*.*.*.0.0.31 = 31
.*.*.*.*.*.*.0.0.32 = 32
.*.*.*.*.*.*.0.0.33 = 33
.*.*.*.*.*.*.0.0.34 = 34
.*.*.*.*.*.*.0.0.35 = 35
.*.*.*.*.*.*.0.0.36 = 36
.*.*.*.*.*.*.0.0.37 = 37
.*.*.*.*.*.*.0.0.38 = 38
.*.*.*.*.*.*.0.0.39 = 39
.*.*.*.*.*.*.0.0.40 = 40
.*.*.*.*.*.*.0.0.41 = 41
.*.*.*.*.*.*.0.0.42 = 42
.*.*.*.*.*.*.0.0.43 = 43
.*.*.*.*.*.*.0.0.44 = 44
.*.*.*.*.*.*.0.0.45 = 45
.*.*.*.*.*.*.0.0.46 = 46
.*.*.*.*.*.*.0.0.47 = 47
.*.*.*.*.*.*.0.0.48 = 48
.*.*.*.*.*.*.0.0.49 = 49
.*.*.*.*.*.*.0.0.50 = 50
.*.*.*.*.*.*.0.0.51 = 51
.*.*.*.*.*.*.0.0.52 = 52
.*.*.*.*.*.*.0.0.53 = 53
.*.*.*.*.*.*.0.0.54 = 54
.*.*.*.*.*.*.0.0.55 = 55
.*.*.*.*.*.*.0.0.56 = 56
.*.*.*.*.*.*.0.0.57 = 57
.*.*.*.*.*.*.0.0.1 = "CPU Temperature-Ctlr B"
.*.*.*.*.*.*.0.0.2 = "Capacitor Pack Temperature-Ctlr B"
.*.*.*.*.*.*.0.0.3 = "Expander Temperature-Ctlr B"
.*.*.*.*.*.*.0.0.4 = "Disk Controller Temperature-Ctlr B"
.*.*.*.*.*.*.0.0.5 = "Host Left IOC Temperature-Ctlr B"
.*.*.*.*.*.*.0.0.6 = "CPU Temperature-Ctlr A"
.*.*.*.*.*.*.0.0.7 = "Capacitor Pack Temperature-Ctlr A"
.*.*.*.*.*.*.0.0.8 = "Expander Temperature-Ctlr A"
.*.*.*.*.*.*.0.0.9 = "Disk Controller Temperature-Ctlr A"
.*.*.*.*.*.*.0.0.10 = "Host Left IOC Temperature-Ctlr A"
.*.*.*.*.*.*.0.0.11 = "Capacitor Pack Voltage-Ctlr B"
.*.*.*.*.*.*.0.0.12 = "Capacitor Cell 1 Voltage-Ctlr B"
.*.*.*.*.*.*.0.0.13 = "Capacitor Cell 2 Voltage-Ctlr B"
.*.*.*.*.*.*.0.0.14 = "Capacitor Cell 3 Voltage-Ctlr B"
.*.*.*.*.*.*.0.0.15 = "Capacitor Cell 4 Voltage-Ctlr B"
.*.*.*.*.*.*.0.0.16 = "Capacitor Pack Voltage-Ctlr A"
.*.*.*.*.*.*.0.0.17 = "Capacitor Cell 1 Voltage-Ctlr A"
.*.*.*.*.*.*.0.0.18 = "Capacitor Cell 2 Voltage-Ctlr A"
.*.*.*.*.*.*.0.0.19 = "Capacitor Cell 3 Voltage-Ctlr A"
.*.*.*.*.*.*.0.0.20 = "Capacitor Cell 4 Voltage-Ctlr A"
.*.*.*.*.*.*.0.0.21 = "Capacitor Charge-Ctlr B"
.*.*.*.*.*.*.0.0.22 = "Capacitor Charge-Ctlr A"
.*.*.*.*.*.*.0.0.23 = "Overall Unit Status"
.*.*.*.*.*.*.0.0.24 = "SBB IOM Inlet Temperature Loc: lower-IOM B"
.*.*.*.*.*.*.0.0.25 = "Expander Internal Temperature Loc: lower-IOM B"
.*.*.*.*.*.*.0.0.26 = "SBB IOM Inlet Temperature Loc: upper-IOM A"
.*.*.*.*.*.*.0.0.27 = "Expander Internal Temperature Loc: upper-IOM A"
.*.*.*.*.*.*.0.0.28 = "Temperature Inlet Loc: right-PSU"
.*.*.*.*.*.*.0.0.29 = "Temperature Hotspot Loc: right-PSU"
.*.*.*.*.*.*.0.0.30 = "Temperature Inlet Loc: left-PSU"
.*.*.*.*.*.*.0.0.31 = "Temperature Hotspot Loc: left-PSU"
.*.*.*.*.*.*.0.0.32 = "Front-Right Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.33 = "Middle-Left Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.34 = "Rear-Left Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.35 = "Rear-Right Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.36 = "Front-Right Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.37 = "Middle-Left Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.38 = "Rear-Left Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.39 = "Rear-Right Baseplane Temp Loc: Drawer"
.*.*.*.*.*.*.0.0.40 = "24-port Expander, Right Sideplane"
.*.*.*.*.*.*.0.0.41 = "36-port Expander, Right Sideplane"
.*.*.*.*.*.*.0.0.42 = "24-port Expander, Left Sideplane"
.*.*.*.*.*.*.0.0.43 = "36-port Expander, Left Sideplane"
.*.*.*.*.*.*.0.0.44 = "Ambient Temp, Left Sideplane"
.*.*.*.*.*.*.0.0.45 = "24-port Expander, Right Sideplane"
.*.*.*.*.*.*.0.0.46 = "36-port Expander, Right Sideplane"
.*.*.*.*.*.*.0.0.47 = "24-port Expander, Left Sideplane"
.*.*.*.*.*.*.0.0.48 = "36-port Expander, Left Sideplane"
.*.*.*.*.*.*.0.0.49 = "Ambient Temp, Left Sideplane"
.*.*.*.*.*.*.0.0.50 = "Voltage 12V Rail Loc: right-PSU"
.*.*.*.*.*.*.0.0.51 = "Voltage 5V Rail Loc: right-PSU"
.*.*.*.*.*.*.0.0.52 = "Voltage 12V Rail Loc: left-PSU"
.*.*.*.*.*.*.0.0.53 = "Voltage 5V Rail Loc: left-PSU"
.*.*.*.*.*.*.0.0.54 = "Current 12V Rail Loc: right-PSU"
.*.*.*.*.*.*.0.0.55 = "Current 5V Rail Loc: right-PSU"
.*.*.*.*.*.*.0.0.56 = "Current 12V Rail Loc: left-PSU"
.*.*.*.*.*.*.0.0.57 = "Current 5V Rail Loc: left-PSU"
.*.*.*.*.*.*.0.0.1 = 3
.*.*.*.*.*.*.0.0.2 = 3
.*.*.*.*.*.*.0.0.3 = 3
.*.*.*.*.*.*.0.0.4 = 3
.*.*.*.*.*.*.0.0.5 = 3
.*.*.*.*.*.*.0.0.6 = 3
.*.*.*.*.*.*.0.0.7 = 3
.*.*.*.*.*.*.0.0.8 = 3
.*.*.*.*.*.*.0.0.9 = 3
.*.*.*.*.*.*.0.0.10 = 3
.*.*.*.*.*.*.0.0.11 = 3
.*.*.*.*.*.*.0.0.12 = 3
.*.*.*.*.*.*.0.0.13 = 3
.*.*.*.*.*.*.0.0.14 = 3
.*.*.*.*.*.*.0.0.15 = 3
.*.*.*.*.*.*.0.0.16 = 3
.*.*.*.*.*.*.0.0.17 = 3
.*.*.*.*.*.*.0.0.18 = 3
.*.*.*.*.*.*.0.0.19 = 3
.*.*.*.*.*.*.0.0.20 = 3
.*.*.*.*.*.*.0.0.21 = 3
.*.*.*.*.*.*.0.0.22 = 3
.*.*.*.*.*.*.0.0.23 = 3
.*.*.*.*.*.*.0.0.24 = 3
.*.*.*.*.*.*.0.0.25 = 3
.*.*.*.*.*.*.0.0.26 = 3
.*.*.*.*.*.*.0.0.27 = 3
.*.*.*.*.*.*.0.0.28 = 3
.*.*.*.*.*.*.0.0.29 = 3
.*.*.*.*.*.*.0.0.30 = 3
.*.*.*.*.*.*.0.0.31 = 3
.*.*.*.*.*.*.0.0.32 = 3
.*.*.*.*.*.*.0.0.33 = 3
.*.*.*.*.*.*.0.0.34 = 3
.*.*.*.*.*.*.0.0.35 = 3
.*.*.*.*.*.*.0.0.36 = 3
.*.*.*.*.*.*.0.0.37 = 3
.*.*.*.*.*.*.0.0.38 = 3
.*.*.*.*.*.*.0.0.39 = 3
.*.*.*.*.*.*.0.0.40 = 3
.*.*.*.*.*.*.0.0.41 = 3
.*.*.*.*.*.*.0.0.42 = 3
.*.*.*.*.*.*.0.0.43 = 3
.*.*.*.*.*.*.0.0.44 = 3
.*.*.*.*.*.*.0.0.45 = 3
.*.*.*.*.*.*.0.0.46 = 3
.*.*.*.*.*.*.0.0.47 = 3
.*.*.*.*.*.*.0.0.48 = 3
.*.*.*.*.*.*.0.0.49 = 3
.*.*.*.*.*.*.0.0.50 = 3
.*.*.*.*.*.*.0.0.51 = 3
.*.*.*.*.*.*.0.0.52 = 3
.*.*.*.*.*.*.0.0.53 = 3
.*.*.*.*.*.*.0.0.54 = 3
.*.*.*.*.*.*.0.0.55 = 3
.*.*.*.*.*.*.0.0.56 = 3
.*.*.*.*.*.*.0.0.57 = 3
.*.*.*.*.*.*.0.0.1 = ""
.*.*.*.*.*.*.0.0.2 = ""
.*.*.*.*.*.*.0.0.3 = ""
.*.*.*.*.*.*.0.0.4 = ""
.*.*.*.*.*.*.0.0.5 = ""
.*.*.*.*.*.*.0.0.6 = ""
.*.*.*.*.*.*.0.0.7 = ""
.*.*.*.*.*.*.0.0.8 = ""
.*.*.*.*.*.*.0.0.9 = ""
.*.*.*.*.*.*.0.0.10 = ""
.*.*.*.*.*.*.0.0.11 = ""
.*.*.*.*.*.*.0.0.12 = ""
.*.*.*.*.*.*.0.0.13 = ""
.*.*.*.*.*.*.0.0.14 = ""
.*.*.*.*.*.*.0.0.15 = ""
.*.*.*.*.*.*.0.0.16 = ""
.*.*.*.*.*.*.0.0.17 = ""
.*.*.*.*.*.*.0.0.18 = ""
.*.*.*.*.*.*.0.0.19 = ""
.*.*.*.*.*.*.0.0.20 = ""
.*.*.*.*.*.*.0.0.21 = ""
.*.*.*.*.*.*.0.0.22 = ""
.*.*.*.*.*.*.0.0.23 = ""
.*.*.*.*.*.*.0.0.24 = ""
.*.*.*.*.*.*.0.0.25 = ""
.*.*.*.*.*.*.0.0.26 = ""
.*.*.*.*.*.*.0.0.27 = ""
.*.*.*.*.*.*.0.0.28 = ""
.*.*.*.*.*.*.0.0.29 = ""
.*.*.*.*.*.*.0.0.30 = ""
.*.*.*.*.*.*.0.0.31 = ""
.*.*.*.*.*.*.0.0.32 = ""
.*.*.*.*.*.*.0.0.33 = ""
.*.*.*.*.*.*.0.0.34 = ""
.*.*.*.*.*.*.0.0.35 = ""
.*.*.*.*.*.*.0.0.36 = ""
.*.*.*.*.*.*.0.0.37 = ""
.*.*.*.*.*.*.0.0.38 = ""
.*.*.*.*.*.*.0.0.39 = ""
.*.*.*.*.*.*.0.0.40 = ""
.*.*.*.*.*.*.0.0.41 = ""
.*.*.*.*.*.*.0.0.42 = ""
.*.*.*.*.*.*.0.0.43 = ""
.*.*.*.*.*.*.0.0.44 = ""
.*.*.*.*.*.*.0.0.45 = ""
.*.*.*.*.*.*.0.0.46 = ""
.*.*.*.*.*.*.0.0.47 = ""
.*.*.*.*.*.*.0.0.48 = ""
.*.*.*.*.*.*.0.0.49 = ""
.*.*.*.*.*.*.0.0.50 = ""
.*.*.*.*.*.*.0.0.51 = ""
.*.*.*.*.*.*.0.0.52 = ""
.*.*.*.*.*.*.0.0.53 = ""
.*.*.*.*.*.*.0.0.54 = ""
.*.*.*.*.*.*.0.0.55 = ""
.*.*.*.*.*.*.0.0.56 = ""
.*.*.*.*.*.*.0.0.57 = ""
.*.*.*.*.*.*.0.0.1 = "CPU Temperature-Ctlr B: 60 C 140.00F"
.*.*.*.*.*.*.0.0.2 = "Capacitor Pack Temperature-Ctlr B: 37 C 98.60F"
.*.*.*.*.*.*.0.0.3 = "Expander Temperature-Ctlr B: 63 C 145.40F"
.*.*.*.*.*.*.0.0.4 = "Disk Controller Temperature-Ctlr B: 68 C 154.40F"
.*.*.*.*.*.*.0.0.5 = "Host Left IOC Temperature-Ctlr B: 51 C 123.80F"
.*.*. [...]

2024-12-08 14:50 UTC, PipoCanaja commented
Hello @TheMysteriousX 
What is the status of this PR from your PoV ? do you have things to add ? Or can it be reviewed ?

2024-12-10 01:51 UTC, TheMysteriousX commented
As far as I'm concerned it's ready - I know there's a preference to YAML sensors but unless Dell start publishing the sensor data in a proper table (device is end of sale, so unlikely) or some more features get added to the YAML sensor definition, I don't see a way to implement it.

The test data included is everything for sensors being returned - it does not correctly or fully implement FCMGMT-MIB despite using the OID.

The constraints are:
* The ordering is not stable across reboots
* The number of sensors is not stable across model variations
* The sensor values are embedded in the name of the sensor so you need to parse the string.

2024-12-15 01:55 UTC, laf approved these changes
LGTM

2024-12-15 01:56 UTC, merged