Add 'to' parameter where missing to fix a graph visualization issue
librenms/librenms pull request #15840
Opened 2024-02-19 15:39 UTC by sina-4

When analyzing a graph and selecting a custom 'to' date, it consistently defaults to the current date and time.

After encountering this issue, I found a workaround on the LibreNMS forum, which involves manually adding the 'to' parameter in the URL. Upon inspecting the source code, I discovered that the 'to' parameter is missing several times when generating the URL.

This pull request highlights the locations where I have added the 'to' parameter.

I have tested these changes, and now the custom 'to' parameter is being considered. 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-02-19 15:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=15840) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=15840) before we can accept your contribution.<br/><hr/>**akabli** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=15840) it.</sub>

2024-03-12 07:19 UTC, PipoCanaja commented
Hi @sina-4 
Could you by chance sort the license/CLA point out ? 
Thanx

2024-03-24 19:16 UTC, PipoCanaja commented
Hi @sina-4 
Seems that the Contributor License Agreement is not signed yet.

According to the CLA test : 
**akabli** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2024-04-01 19:25 UTC, murrant requested changes
to parameter is intended to be omitted when using from=-1d
Otherwise, refreshing the page always shows the same time period.

I don't understand what your issue is, but your fix will break other things.

2024-04-01 19:27 UTC, murrant commented on app/Http/Controllers/Table/MempoolsController.php
> +        $link = Url::generate(['page' => 'graphs'], Arr::only($graph, ['id', 'type', 'from','to']));
This is the correct fix.

2024-04-01 19:27 UTC, murrant commented on includes/html/pages/device/overview/mempools.inc.php
> +        $link = Url::generate(['page' => 'graphs'], Arr::only($graph_array, ['id', 'type', 'from','to']));
And this.

2024-04-01 19:29 UTC, murrant commented on app/Http/Controllers/Table/MempoolsController.php
> +            'to' => Config::get('time.now') ,
```suggestion
            'from' => '-1d',
```

2024-04-01 19:30 UTC, murrant commented on LibreNMS/Util/Html.php
> +            $graph_array['to'] = Config::get("time.now");
```suggestion
```

2024-04-01 19:30 UTC, murrant commented on includes/html/functions.inc.php
> +    $url = \LibreNMS\Util\Url::generate(['page' => 'graphs', 'id' => $args['sensor_id'], 'type' => $args['graph_type'], 'from' => \LibreNMS\Config::get('time.day'), 'to' => \LibreNMS\Config::get('tim
```suggestion
    $url = \LibreNMS\Util\Url::generate(['page' => 'graphs', 'id' => $args['sensor_id'], 'type' => $args['graph_type'], 'from' => '-1d'], []);
```

2024-04-14 21:48 UTC, closed without merging