Option for read-only user access Oxidized configs
librenms/librenms pull request #15951
Opened 2024-04-17 13:16 UTC by bnoack-stepcg

Created option in oxidized settings to allow read only users to access Oxidized configs.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-04-17 13:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=15951) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=15951) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=15951) it.</sub>

2024-04-18 12:20 UTC, Jellyfrog requested changes
There is a RBAC system now in librenms and we would like to start using that for authorization

2024-04-18 14:51 UTC, electrocret approved these changes
LGTM. Seems like an acceptable stop-gap till we get RBAC fully developed.

2024-04-18 14:53 UTC, electrocret requested changes
Just noticed Jelly's comment. I guess RBAC is further along than I thought.

2024-09-02 11:46 UTC, Spleeff commented
Hello,

Do you have an estimated date for the implementation of this feature ?

Thanks

2024-12-09 13:32 UTC, laf commented
@librenms/core Thoughts on merging this as is (with some documentation?) I don't think the current RBAC gives us anything that could improve this PR currently.

2025-04-05 22:40 UTC, laf approved these changes
LGTM

2025-04-13 08:28 UTC, merged

2025-04-13 23:25 UTC, murrant commented
I don't like this, sorry, it just makes a mess.

RBAC is not that far off at all, the main problem is it has UI bits and creating UI sucks :)