[DOC] Install LibreNMS: add Icons
librenms/librenms pull request #15989
Opened 2024-04-27 16:56 UTC by santiag0z

Please give a short description what your pull request is for

![image](https://github.com/librenms/librenms/assets/34222550/e3e00841-5cb8-456c-b9a8-1e3e409f7dbc)

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-04-27 23:02 UTC, murrant submitted a review, later dismissed

2024-04-27 23:03 UTC, murrant commented
You'll need to update the CI build (and documentation) to include the additional modules

2024-04-28 02:18 UTC, santiag0z commented
@murrant, I can't resolve the following error:

_Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'material.extensions.emoji' (No module named 'material.extensions')
  in "/docs/mkdocs.yml", line 40, column 20
Error: Process completed with exit code 1._

2024-04-28 15:42 UTC, Jellyfrog requested changes

2024-04-28 15:42 UTC, Jellyfrog commented on .github/workflows/doc.yml
> +          python-version: 3.x
This is wrong. Extensions are installed inside the dckerrfile.

2024-04-28 23:43 UTC, santiag0z commented
@murrant and @Jellyfrog 

According to the pymdown-extensions documentation, `pip install pymdown-extensions` was supposed to be sufficient.

Looking at the problem below, sometimes you need `pip install pymdown-extensions` `pip install mkdocs-material-extensions` `pip install mkdocs-material`
https://github.com/facelessuser/pymdown-extensions/issues/110

But I only had success after updating mkdocs-material version 8.3.9 -> 9.5.19

2024-04-29 14:33 UTC, murrant approved these changes
Thanks for updating, looks good now.  I didn't test build this locally, but should work.

2024-04-29 14:34 UTC, merged

2024-04-29 19:28 UTC, murrant commented
@santiag0z dang, still didn't build right on CI. https://github.com/librenms/librenms/actions/runs/8884133091/job/24392532294

2024-04-29 19:46 UTC, santiag0z commented
putz| I was sad, I'm going to check it calmly and test it first by updating and then with the modification.