Allow for more than one instance of device_id to be replaced in the a…
librenms/librenms pull request #15993
Opened 2024-04-29 16:38 UTC by dethmetaljeff

This will allow for more than one instance of ? to be replaced by device_id in a custom alertrule.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-05-01 15:50 UTC, murrant requested changes
I don't see why this would be desirable.

2024-05-01 15:52 UTC, dethmetaljeff commented
> I don't see why this would be desirable.

If you have a custom SQL alert rule and need device_id in the SQL more than once you currently can't do it.  Assuming the query can't be refactored to not need the parameter more than once for whatever reason.

2024-05-03 23:33 UTC, murrant commented
If you need a second instance of device_id simply do <table>.device_id = devices.device_id.

2024-05-03 23:33 UTC, closed without merging

2024-05-06 15:38 UTC, chris-ruddy commented
@murrant I need this feature for filtering in multiple subqueries.