Create Alertops.php
librenms/librenms pull request #16050
Opened 2024-05-21 18:11 UTC by ashwath129

This is a request to add this Transport publicly, so alerts can be sent to AlertOps' webhook endpoint - AlertOps is an alerting/notification tool. (https://alertops.com/)

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-05-21 18:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=16050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=16050) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=16050) it.</sub>

2024-05-22 15:25 UTC, electrocret requested changes
Please add documentation to doc/Alerting/Transports.md on how to configure this Alert Transport.

2024-05-22 19:45 UTC, ashwath129 commented
> Please add documentation to doc/Alerting/Transports.md on how to configure this Alert Transport.

Sure did this ! - #16058

2024-05-23 02:37 UTC, murrant commented
@ashwath129 can you please put the docs in this PR (that way it is easy to find them later).
If you don't know how to do that, come ask on Discord.

2024-05-23 03:03 UTC, electrocret approved these changes

2024-05-23 03:03 UTC, merged

2024-05-23 03:08 UTC, electrocret commented
@murrant , sorry didn't see your comment before approving these. 

Yeah, it's best practice to have all the changes under a single PR, however in this instance it shouldn't be too much of an inconvenience since it's just a single transport that doesn't seem to have anything out of the ordinary going on.