Created IBM On Call Manager Alert Transport
librenms/librenms pull request #16395
Opened 2024-09-13 14:35 UTC by SaneiSaya

Created IBM On Call Manager Alert Transport

I created an alert transport for IBM On Call Manager that will show in the drop down list

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-09-13 14:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=16395) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=16395) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=16395) it.</sub>

2024-09-13 16:14 UTC, murrant commented
Hello, Jayna, thanks for your pull request! Looks like your alert transport is based on older LibreNMS code.  You will need to update it to include it upstream.

2024-09-13 16:14 UTC, SaneiSaya commented on LibreNMS/Alert/Transport/Ibmocm.php
> +        curl_setopt($curl, CURLOPT_URL, $url);
I'll get it updated, I'm going through some of the checks now

2024-09-13 18:17 UTC, SaneiSaya commented on LibreNMS/Alert/Transport/Ibmocm.php
> +        curl_setopt($curl, CURLOPT_URL, $url);
It's updated now with the new code.

2024-09-16 22:42 UTC, SaneiSaya commented
@murrant Do I need to do anything additional before this gets reviewed?

2024-09-28 21:44 UTC, laf commented
@SaneiSaya Thanks for submitting this. Code looks good now but just a couple of points:

1. Can you update `doc/Alerting/Transports.md` to add instructions on how to use it.
2. Is their any public documentation for IBM On Call Manager?
3. Does the webhook just accept any arbitrary data sent to it as `$alert_data` is passed across and I'm just wondering how that then gets used.

2024-10-03 17:21 UTC, SaneiSaya commented
1. I updated the file
2. There is no public documents I can find, they must be internal only
3. The webhook will accept any data, but with the plugin I made it wi;; send the following to On Call Manager: the name or ip address of the system sending the alert, the name of the alert, the severity, timestamp, the OS, location, and the unique id

2024-10-04 13:30 UTC, laf commented
> 1. I updated the file
> 2. There is no public documents I can find, they must be internal only
> 3. The webhook will accept any data, but with the plugin I made it will send the following to On Call Manager: the name or ip address of the system sending the alert, the name of the alert, the severity, timestamp, the OS, location, and the unique id

Thanks, on #3, is that the plugin you've created for IBM on call manager? If so, does that need adding to the IBM system by the user and if so, can you update the docs in this PR to indicate this and how people go about obtaining the plugin.

2024-10-05 17:28 UTC, SaneiSaya commented
For number 3 it is the plugin I created for IBM On Call Manager. I added that to the docs already. Do you need additional information, or for me to post information somewhere else?

2024-10-05 18:24 UTC, laf commented
I'm wondering how a user of IBM call manager gets the LibreNMS plugin that would allow them to use this transport if it's not documented anywhere?

2024-10-06 00:45 UTC, SaneiSaya commented
It's going to be in the pull down list

On Sat, Oct 5, 2024 at 12:24 PM Neil Lathwood ***@***.***>
wrote:

> I'm wondering how a user of IBM call manager gets the LibreNMS plugin that
> would allow them to use this transport if it's not documented anywhere?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/librenms/librenms/pull/16395#issuecomment-2395142387>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFJLQ3NQGDGYNMYUQAR7LYTZ2AVG3AVCNFSM6AAAAABOFQIPJSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGE2DEMZYG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-06 20:40 UTC, laf commented
> It's going to be in the pull down list

So it's natively supported within IBM call manager?

2024-10-07 02:08 UTC, SaneiSaya commented
Yes, I created a plugin for the IBM On Call Manager for LibreNMS as well
and they have approved it already.

On Sun, Oct 6, 2024 at 2:41 PM Neil Lathwood ***@***.***>
wrote:

> It's going to be in the pull down list
>
> So it's natively supported within IBM call manager?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/librenms/librenms/pull/16395#issuecomment-2395578282>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFJLQ3KRPC3PCZUOG4A3RZTZ2GN6VAVCNFSM6AAAAABOFQIPJSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGU3TQMRYGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-07 08:54 UTC, laf requested changes

2024-10-07 08:54 UTC, laf commented on doc/Alerting/Transports.md
> +| API Key | randomsample |
API Key isn't an option in the transport you created.

You also need to document the ocm-url option you have set in the transport.

2024-10-16 21:33 UTC, SaneiSaya commented
Requested update added

2024-11-04 15:42 UTC, laf approved these changes
LGTM. Thanks for contributing

2024-11-04 15:42 UTC, merged