Fix icmp service only having packet loss graph
librenms/librenms pull request #16479
Opened 2024-10-02 10:48 UTC by zippanto

Currently there is an issue with icmp service. If upon creation there is no icmp reply the output of the check_icmp command only contains the packet loss:

```
# /usr/lib/monitoring-plugins/check_icmp -H 1.1.1.1
CRITICAL - 1.1.1.1: rta nan, lost 100%|pl=100%;40;80;0;100
```

This then causes two issues internally:
1. The RRD file gets created with only the packet loss data source and the additional data sources will not get added even after there is an icmp reply (and so output from check_icmp containing the full dataset)
2. On creation the service_ds column is set to `{}`. During the first update the service_ds column in the database gets updated, but this is based on the output of the check_icmp command. So if there is no icmp reply it will only add the packet loss into service_ds. There will be no further updates to the service_ds column as with the current logic this only happens if the value of the service_ds column is blank or `{}`.

Ultimately this means that the service will only ever show a packet loss graph and the RRD file will only contain data for packet loss, even after receiving icmp replies. Once icmp replies are being received deleting the RRD file doesn't fix the issue as the value in the service_ds column in the database is still incorrect. Both the RRD file and the value in the service_ds column needs to be fixed OR the service needs to be recreated.

The changes in this PR aim to fix the above internal issues by making the below changes:

1. Move the definition of the `$check_ds` variable outside of the `isset($rrd_filename)` condition in `includes/services/check_icmp.inc.php`

My understanding is that this condition is only met when the `includes/services/check_icmp.inc.php` file is included in `includes/html/graphs/service/graph.inc.php`.

The purpose of moving this definition outside the condition is so we have access to a full definition of the data sources that we are expecting when there is an icmp reply and so we can use this definition to create the RRD file with all the data sources as well as use the definition to update the service_ds column in the database setting it's value to the full dataset.

Moving this definition outside the condition shouldn't (or just barely) impact performance.

I have noticed there is a similar definition in `includes/services/check_load.inc.php` and `includes/services/check_mysql.inc.php`. I wasn't able to confirm if these service types are affected by the same issue or not. It might be that they are also affected and moving the definition outside the condition in these files would fix the issue.

2. Conditional value assignment to `$DS` variable in `includes/services.inc.php` function `poll_service`

If condition `isset($check_ds)` is true we iterate through `json_decode($check_ds)` (instead of `$perf`) to generate the data sources (`$DS`). If the condition is false we iterate through `$perf` (this is following the unconditional original code) to generate the data sources.

In the original code the `$DS` variable is only used to update the service_ds column. Please see change 3 below where we will make additional use of this variable.

The addition of this condition should only affect the icmp, load and mysql services as these are the only services defining the `$check_ds` variable. All other services should follow the false branch of the condition and so will be using the original code.

3. Change `$rrd_def` value to be generated from `$DS` instead of `$perf`

Since the original code used to generate the value of `$DS` from `$perf` this should not make any practical difference for any service following the false branch of the condition mentioned in change 2 (see above). For the services following the true branch (as per the description in change 2 this should only be the services icmp, load and mysql) it will change the value of `$rrd_def` to be the full dataset.

4. Change condition `$v['uom'] == 'c' to `$v == 'c'` to determine if a data source is a counter

This change is required as a consequence of change 3 (see above). The items in the `$perf` array are an array per data source, containing an item for the value and an item for unit of measure. The items in the `$DS` array are a string per data source with the value for the unit of measure. Please see below for the difference in data structure.

```
$perf: Array
(
    [pl] => Array
        (
            [value] => 100
            [uom] => %
        )

)
```

vs.

```
$DS: Array
(
    [rta] => s
    [rtmax] => s
    [rtmin] => s
    [pl] => %
)
```

Please note my understanding of the LibreNMS code is not complete and this PR is only a best effort attempt to make an optimal change to fix the issue described. Any criticism or comments are welcome.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2026-05-11 11:19 UTC, zippanto commented
Hi @murrant,

Why was this closed? If there is anything I need to change or add please let me know.

Thanks.

2026-05-14 13:01 UTC, PipoCanaja commented
Hi @zippanto 
Let's reopen this one. As @murrant already told you on Discord, LLMs created a new problem : flooding the maintainers ...

2026-05-14 13:02 UTC, PipoCanaja commented
I already had the issue you are describing. And not only with check_icmp by the way. Let see how it can be solved here.

2026-05-14 13:04 UTC, PipoCanaja commented
Could you please fix the conflict with current master code ?

2026-05-23 13:32 UTC, murrant commented
This also looks like it will cause breaking changes.

2026-06-01 09:44 UTC, zippanto commented
@PipoCanaja Thanks. I have fixed the conflict. I can't really comment on the other services as we only use the ICMP one, there might be a better approach to address this issue globally. 

@murrant Could you please elaborate?

2026-06-01 10:52 UTC, PipoCanaja commented on includes/services.inc.php
> +        if (isset($check_ds)) {
`$check_ds` will never be set here, or do I miss something ?

2026-06-01 10:52 UTC, PipoCanaja requested changes

2026-06-01 11:03 UTC, zippanto commented on includes/services.inc.php
> +        if (isset($check_ds)) {
https://github.com/librenms/librenms/pull/16479/changes/BASE..60187d937ce2875c29ec0200da1f1611ad4da126#diff-275f0ba19b981f75db106a46ddd955890665e0f2b6be0c62988016134e7c99c2R65 There is an include on line 65 - in this instance `$check_ds` is set in check_icmp.inc.php

2026-06-26 02:52 UTC, murrant commented
Thanks for your pull request. You haven't updated this PR in some time. Closing it for now.

Please feel free to reopen, I would love to see your changes added to LibreNMS.

2026-06-26 10:15 UTC, zippanto commented
> Thanks for your pull request. You haven't updated this PR in some time. Closing it for now.
> 
> Please feel free to reopen, I would love to see your changes added to LibreNMS.

@murrant I'm sorry I'm confused. There is an on-going conversation based on the requested changes from @PipoCanaja, however I haven't received any replies for a while now. If I need to make further changes it's not clear what these are. If you need me to provide any more information please do let me know.

I don't seem to have the option to reopen the issue.

2026-06-26 11:41 UTC, murrant commented
You never fixed the ci failure.  It was sitting in that state for a long time.

2026-06-26 12:48 UTC, zippanto commented
> You never fixed the ci failure. It was sitting in that state for a long time.

Please see the conversation. The CI failure is caused by ds_check being defined in another file that is being included. I'm unsure what is the correct way to resolve the CI failure so any suggestions are welcome, or just a nudge in the right direction.

2026-06-26 14:56 UTC, murrant commented
I'm confident you can figure this out.  There are multiple options I would accept.  I'm not here to do your homework (sorry if I come off as cold, I've been abused by AI)

2026-06-26 15:00 UTC, zippanto commented
> I'm confident you can figure this out. There are multiple options I would accept. I'm not here to do your homework (sorry if I come off as cold, I've been abused by AI)

That's fair enough. I just feel like the changes that would be required to address the issue with the CI failure is beyond the scope of this change / pull request. I'll wait for @PipoCanaja perhaps he has some suggestion. Otherwise I'll spend some time to research.

2026-06-26 16:01 UTC, zippanto commented
@murrant It seems there is a way to tell PHPStan (the Lint / PHP Static Analysis tool) to ignore this specific error by assuring that the variable is indeed defined (for reference https://github.com/phpstan/phpstan/issues/5815#issuecomment-998937556). Is this something that you'd be happy with? As the comment points out it would be a more appropriate fix to change the code style to avoid these kind of include related issues, but as I mentioned before I feel like this is beyond the scope of this pull request. I'd think based on the nature of the code that is triggering this error - eg. we're checking if the variable is defined - this CI error could be ignored. Please let me know your thoughts. Thanks.

2026-06-28 14:32 UTC, murrant commented
All you need is a phpdoc variable annotation `@var`.  This isn't a phpstan deficiency it is a deficiency of old old code that designed to use PHP files like they are functions, passing in random variables to the file.

2026-07-02 15:51 UTC, murrant commented
I tried to test this, but nothing works.  check_icmp call fails with wrong format.
ds fields from the script are odd.
using this makes the ds not match the fields returned from check_icmp

2026-07-24 09:08 UTC, zippanto commented
When I rebased the changes just recently I haven't checked if the issue is fixed in master. I have just tested this again in master and it already seems to be fixed. Therefore this PR is unnecessary.

2026-07-24 09:08 UTC, closed without merging