Dell sensor fix variable leaking
librenms/librenms pull request #16511
Opened 2024-10-08 15:44 UTC by TridTech

Dell sensor additions were setting variables that leaked to the next includes, leading to zeros being populated in fields they did not belong in.  Zeros were being set for voltages and temperatures in the warning areas when no value was set on the device, leading to warn status on devices.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-10-08 17:17 UTC, laf commented on includes/discovery/sensors/fanspeed/dell.inc.php
> +        if (isset($temp[$index]['coolingDeviceReading'])) {
Well spotted with these.

To just tidy things up can you shorten these to:

`(isset($temp[$index]['coolingDeviceLowerCriticalThreshold'])) ? $value = $temp[$index]['coolingDeviceReading'] : $value = null;`

2024-10-08 17:18 UTC, laf requested changes
Well spotted, I've just made a suggestion on how to shorten the code down if you can apply that logic to the rest of the code that would be ace.

2024-10-08 18:36 UTC, TridTech commented
> Well spotted, I've just made a suggestion on how to shorten the code down if you can apply that logic to the rest of the code that would be ace.

That makes it look a lot cleaner.  They are all shortened.

2024-10-09 07:24 UTC, laf approved these changes
LGTM

2024-10-09 07:24 UTC, merged