Popover fixes on transports page
librenms/librenms pull request #16527
Opened 2024-10-11 21:53 UTC by alwold

When viewing the alert transports, there are a few issues with the popovers on the action buttons on the right side of the screen:
- For the buttons that trigger a dialog, they seemed not to show the popover at all, since they had two `data-toggle` attributes on the HTML element. I changed the popovers to use a dedicated `data-popover` attribute instead, so they wouldn't clash with the modal setup.
- For the "Test Transport" button, the top of the popover was cut off for me, so I could only see the "Transport" part of the text. I added `container: 'body'` for the popovers to fix this, which I believe is making it higher up in the DOM, so other elements aren't obscuring it.

Here's the page in question, showing the now working popup for Test Transport:

<img width="1121" alt="Screenshot 2024-10-11 at 10 00 00 AM" src="https://github.com/user-attachments/assets/46b088a4-3f5b-4c8e-ada3-b0ab7c4d49c3">

This is my first PR, so definitely let me know if anything should be done differently.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-10-11 21:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/librenms/librenms?pullRequest=16527) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/librenms/librenms?pullRequest=16527) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/librenms/librenms?pullRequest=16527) it.</sub>

2024-10-11 22:22 UTC, murrant approved these changes

2024-10-11 22:23 UTC, murrant requested changes
You should probably remove `data-container='body'`

2024-10-12 14:31 UTC, alwold commented
> You should probably remove `data-container='body'`

Good call, I didn't even notice that. I'll remove it and verify everything still works with the modals. It looks like the "Test Transport" button is the one button that doesn't have `data-container='body'` already, so I guess that's why it was getting truncated.

2024-10-13 20:53 UTC, laf approved these changes
LGTM and thanks for contributing @alwold :)

2024-10-13 20:54 UTC, merged