Fix for FortiGate discovery - Issue ID #16544
librenms/librenms pull request #16753
Opened 2024-11-22 14:53 UTC by rudybroersma

This patch fixes two sensors in which discovery did not add a value (causing it to go back to 0 / null):

- FortiGate license expiration sensors
- FortiGate HA sync sensor

I did *NOT* add test data, because current CI/CD pipeline can't cope with the license expiration sensors because the output will differ each day. IIRC that requires manual intervention by removing test data.. I didn't want to break that

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-11-27 11:37 UTC, laf requested changes
Also, you don't need to submit multiple json test files if we're just testing the same thing each time, one covering a range of models is fine. We also need the snmprec data as well.

2024-11-27 11:37 UTC, laf commented on includes/discovery/sensors/count/fortigate.inc.php
> +            $expirationRaw = snmp_get($device, '.1.3.6.1.4.1.12356.101.4.6.3.1.2.1.2.' . $index, '-OUqnv', 'FORTINET-FORTIGATE-MIB');
We already have this OID is fgLicContractExpiry, is it not in the format you want? If not try adjusting the snmp walk above it to get the output you need without breaking anything.

2024-11-27 11:37 UTC, laf commented on includes/discovery/sensors/state/fortigate.inc.php
> +        $sensor_value = snmp_get($device, $fgHaStatsSyncStatus_txt . '.' . $index, '-OeQv', 'FORTINET-FORTIGATE-MIB');
Looks like we do nothing with `$fgHaStatsSyncStatus_txt` before hand other than set it and unset it so you can safely append the `$index` to the variable a few lines above.

2024-12-28 23:46 UTC, laf commented
@rudybroersma any response to the above comments?

2025-01-03 19:59 UTC, rudybroersma commented
> @rudybroersma any response to the above comments?

My bad, I thought this was merged already. I'll work on a better fix

2025-01-06 18:02 UTC, rudybroersma commented on includes/discovery/sensors/count/fortigate.inc.php
> +            $expirationRaw = snmp_get($device, '.1.3.6.1.4.1.12356.101.4.6.3.1.2.1.2.' . $index, '-OUqnv', 'FORTINET-FORTIGATE-MIB');
> We already have this OID is fgLicContractExpiry, is it not in the format you want? If not try adjusting the snmp walk above it to get the output you need without breaking anything.

This OID returns a human-readable string representation of a DateTime object. It's useless within LibreNMS. I convert this to UNIX epoch, subtract current epoch to get the number of seconds remaining till license expiration. This is divided by 86400 to get to remaining days till expiration.

SNMP Walk doesn't offer a way to do this

2025-01-06 18:39 UTC, rudybroersma commented
Not sure what the deal is with the tests (again). Breaks on OSPF, while my changes have nothing to do with OSPF

2025-01-06 18:55 UTC, rudybroersma commented
> Not sure what the deal is with the tests (again). Breaks on OSPF, while my changes have nothing to do with OSPF

I removed the FortiGate 500D Test data. Perhaps we should remove the SNMPrec as well?
The 500D is EoS since 2023. It's the only device that breaks tests

2025-01-06 18:57 UTC, rudybroersma commented
> Also, you don't need to submit multiple json test files if we're just testing the same thing each time, one covering a range of models is fine. We also need the snmprec data as well.

I just updated test data. No new devices. Therefor I don't have new SNMPrec data?

2025-01-06 21:46 UTC, laf approved these changes
LGTM now and thanks for the improvements and refactoring the snmp queries.

2025-01-06 21:46 UTC, merged