PANOS Sensor For Active GPVPN Tunnels
librenms/librenms pull request #16838
Opened 2024-12-08 05:41 UTC by eg2965

Added a PANOS sensor to monitor active GlobalProtect VPN tunnels (aka sessions) as a way to track VPN availability on a PA firewall.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

2024-12-08 05:43 UTC, eg2965 commented
Adding screenshots of my Dev instance

![PANOS-GPVPN-Settings-Health-Tab](https://github.com/user-attachments/assets/6c11e9af-6351-470c-86ae-2efb140ffaab)

![PANOS-GPVPN-Settings-Health-Tab](https://github.com/user-attachments/assets/dfef5857-d140-4a82-b23f-3ff8565d12c0)

![PANOS-GPVPN-Yaml](https://github.com/user-attachments/assets/9c3367cf-a7a8-46a5-b51d-ebc112d37027)

2024-12-08 09:53 UTC, eg2965 commented
@laf @murrant - I can't seem to get past the mysql and mariadb unit tests. I've tried several test json files, however each time they fail with the message "OS panos: Discovered sensors data does not match that found in tests/data/panos_vsys.json". I've checked that file, and it looks like old PA-3020 testing data. I tried manually copying my GlobalProtect sensor data to the panos_vsys.json file but it stills fails. Unfortunately the error message is not giving me enough information to find the root cause of the issue. Can you assist?

2024-12-08 12:19 UTC, PipoCanaja commented
Hi @eg2965 
For the existing JSON, you need to run only save-test-data.php against them, if they already have GlobalProtect data in the matching SNMPREC. If not, there is absolutely nothing to change.  
And you also need to create a new SNMPREC file for your variant (which will include the GlobalProtect data for sure) and run  save-test-data.php to create the matching JSON.

2024-12-08 19:57 UTC, eg2965 commented
Thanks @PipoCanaja - that was the piece I was missing. I just re-ran the ./scripts/save-test-data.php command with modifiers of -o panos -v 'vsys', and uploaded the modified panos_vsys.json file here. The checks passed! Will submit the pull request for review now.

2024-12-08 20:05 UTC, eg2965 commented
Clearly I submitted way more commits than I would've like to on account of the failing tests. If you guys would prefer me to delete this PR/branch and start fresh, I'd be willing to. Let me know

2024-12-09 07:00 UTC, PipoCanaja commented
> Clearly I submitted way more commits than I would've like to on account of the failing tests. If you guys would prefer me to delete this PR/branch and start fresh, I'd be willing to. Let me know

If you have the result you wanted, we don't care about the amount of commits to reach this state. We'll squash the PR to one commit anyway to merge it so don't worry.

2024-12-09 07:02 UTC, PipoCanaja requested changes

2024-12-09 07:02 UTC, PipoCanaja commented on tests/snmpsim/panos.snmprec
This file as well as the matching JSON are now missing. Could you please restore this one back to its original state, and run save-test-data.php against it to restore je JSON ?

2024-12-09 09:17 UTC, eg2965 commented on tests/snmpsim/panos.snmprec
@PipoCanaja - I took the long road, but finally got there. Everything should be in order now.
Let me know if there's anything else you need before merging.

2024-12-09 11:36 UTC, laf approved these changes
LGTM, thanks for the contribution @eg2965

2024-12-09 11:37 UTC, merged